/**
 * Global App Context
 * Manages: theme (light / dark / system), language (zh / en), market (us / cn / hk)
 *
 * Default language: English
 * Default market: US
 */

"use client";

import {
  createContext,
  useContext,
  useEffect,
  useSyncExternalStore,
  ReactNode,
} from "react";

export type Theme = "light" | "dark" | "system";
export type Lang = "zh" | "en";
export type Market = "us" | "cn" | "hk";

const STORAGE_KEY = "fin-agent-prefs";
const PREFS_CHANGE_EVENT = "fin-agent-prefs-change";
const DEFAULT_PREFS = { theme: "system" as Theme, lang: "en" as Lang, market: "us" as Market };
let cachedPrefsRaw: string | null = null;
let cachedPrefsValue = DEFAULT_PREFS;

interface AppContextValue {
  theme: Theme;
  lang: Lang;
  market: Market;
  setTheme: (t: Theme) => void;
  setLang: (l: Lang) => void;
  setMarket: (m: Market) => void;
}

const AppContext = createContext<AppContextValue | null>(null);

function readPrefs(): { theme: Theme; lang: Lang; market: Market } {
  if (typeof window === "undefined") return DEFAULT_PREFS;
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === cachedPrefsRaw) return cachedPrefsValue;
    cachedPrefsRaw = saved;
    cachedPrefsValue = saved ? { ...DEFAULT_PREFS, ...JSON.parse(saved) } : DEFAULT_PREFS;
    return cachedPrefsValue;
  } catch {
    return DEFAULT_PREFS;
  }
}

export function AppProvider({ children }: { children: ReactNode }) {
  const prefs = useSyncExternalStore(
    (onStoreChange) => {
      window.addEventListener("storage", onStoreChange);
      window.addEventListener(PREFS_CHANGE_EVENT, onStoreChange);
      return () => {
        window.removeEventListener("storage", onStoreChange);
        window.removeEventListener(PREFS_CHANGE_EVENT, onStoreChange);
      };
    },
    readPrefs,
    () => DEFAULT_PREFS
  );
  const { theme, lang, market } = prefs;

  useEffect(() => {
    const root = document.documentElement;
    const apply = (t: Theme) => {
      const isDark =
        t === "dark" ||
        (t === "system" &&
          window.matchMedia("(prefers-color-scheme: dark)").matches);
      root.classList.toggle("dark", isDark);
    };
    apply(theme);
    if (theme === "system") {
      const mq = window.matchMedia("(prefers-color-scheme: dark)");
      const handler = () => apply("system");
      mq.addEventListener("change", handler);
      return () => mq.removeEventListener("change", handler);
    }
  }, [theme]);

  const persist = (next: { theme: Theme; lang: Lang; market: Market }) => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
      window.dispatchEvent(new Event(PREFS_CHANGE_EVENT));
    } catch {}
  };

  const setTheme = (t: Theme) => persist({ theme: t, lang, market });
  const setLang = (l: Lang) => persist({ theme, lang: l, market });
  const setMarket = (m: Market) => persist({ theme, lang, market: m });

  return (
    <AppContext.Provider value={{ theme, lang, market, setTheme, setLang, setMarket }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used inside AppProvider");
  return ctx;
}

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    brand: "fin-agent-pro",
    navMarketUS: "US Stocks",
    navMarketCN: "China A",
    navMarketHK: "Hong Kong",
    navPortfolio: "Portfolio",
    navCompare: "Compare",
    navValuation: "Valuation",
    navAnalysis: "AI Analysis",
    navSettings: "Settings",
    heroTitle: "fin-agent-pro",
    heroSubtitle: "A financial analysis workspace for market context, company risk, valuation frameworks, portfolio diagnostics, and AI-assisted research.",
    heroCTAPrimary: "Explore markets",
    heroCTASecondary: "Learn more",
    heroVisualKnownLabel: "Verified signals",
    heroVisualKnownBody: "Market moves, financial statements, risk models, valuation assumptions, and portfolio exposure — checked against public data.",
    heroVisualUnknownLabel: "Uncertainty map",
    heroVisualUnknownBody: "Model limits, missing data, stale targets, concentration risk, and market-implied assumptions are surfaced instead of hidden.",
    heroVisualEyebrow: "One workspace for clearer investment research",
    heroVisualTitle: "See the signal, the risk, and the assumption.",
    learnMore: "Learn more",
    tryIt: "Try it",

    // Feature sections (homepage scroll narrative)
    featMarketEyebrow: "MARKET OVERVIEW",
    featMarketTitle: "Real-time market pulse.",
    featMarketBody: "S&P 500, NASDAQ, Hang Seng — all in one view. See what's moving across markets at a glance, with currency-aware formatting and live percentage changes.",

    featHeatmapEyebrow: "SECTOR HEATMAP",
    featHeatmapTitle: "See the heat.",
    featHeatmapBody: "News lags. Trading behavior doesn't. This map shows where capital and volatility are concentrating right now — not what to buy, but where to look.",

    featAiEyebrow: "AI FINANCIAL ANALYSIS",
    featAiTitle: "30 seconds. Any company.",
    featAiBody: "Powered by Altman Z-Score, Beneish M-Score, and Claude / GPT-4o. Ask in plain English, get a pro-grade risk read with red flags surfaced — institutional rigor, retail accessibility.",

    featCompareEyebrow: "MULTI-COMPANY COMPARE",
    featCompareTitle: "Side-by-side, Apple-style.",
    featCompareBody: "Compare 2 to 4 companies across financials, risk scores, and valuation multiples. Best-value highlights instantly show you the outlier — the way Apple compares iPhones.",

    featPortfolioEyebrow: "PORTFOLIO DIAGNOSTIC",
    featPortfolioTitle: "Know your concentration.",
    featPortfolioBody: "Weighted risk scoring, sector concentration warnings, red flags per holding. Your portfolio's full X-ray — diagnostic only, never advice. Data stays in your browser.",

    featDcfEyebrow: "VALUATION ENGINE",
    featDcfTitle: "DCF, drivers, and implied assumptions.",
    featDcfBody: "Start with DCF, then switch into framework-aware drivers. Tesla can be decomposed into Auto, Energy, FSD, and Robotaxi, with market-implied assumptions shown explicitly.",
    marketOverviewTitle: "Market Overview",
    marketOverviewSubtitle: "Live indices, sector pulse, and what's moving today.",
    sectorHeatmapTitle: "Sector Heatmap",
    sectorHeatmapSubtitle: "Bigger bubble = more attention · Deeper color = more volatile",
    heatmapBehaviorMantra: "News lags. Trading behavior doesn't.",
    heatmapBehaviorBody: "This map shows where capital and volatility are concentrating right now — not what to buy, but where to look.",
    sectorRankingTitle: "Sector Ranking",
    hkAnalysisTitle: "Analyze any HK-listed company",
    hkAnalysisBody: "Sector heatmaps aren't available for Hong Kong, but you can ask the AI about any HK-listed stock — Tencent (00700), HSBC (00005), Alibaba HK (09988), Xiaomi (01810), and more. Get the same Altman Z-Score / Beneish M-Score / financial breakdown.",
    hkAnalysisCTA: "Ask the AI",
    dataUnavailableTitle: "Market data temporarily unavailable",
    dataUnavailableBody: "The data provider (EastMoney via AkShare) is currently not responding. This is on their side, not yours. AI analysis on individual stocks still works — try the floating chat below.",
    sectorDataUnavailableTitle: "A-share sector data temporarily unavailable",
    sectorDataUnavailableBody: "Index quotes are available, but the EastMoney sector board or fund-flow endpoint returned no usable rows. We'll show cached data when available; individual-stock AI analysis still works.",
    cnFallbackTitle: "Analyze any A-share company",
    cnFallbackBody: "Market overview is currently unavailable, but you can still ask the AI about any A-share stock — Kweichow Moutai (600519), CATL (300750), BYD (002594), and more. Full financial breakdown with Altman Z-Score and Beneish M-Score.",
    cnFallbackCTA: "Ask the AI",
    catIndustry: "Industry",
    catSize: "Size",
    catRegion: "Region",
    viewHeatmap: "Heatmap",
    viewRank: "Ranking",
    todayHottest: "Today's hottest:",
    legendUp: "Up",
    legendDown: "Down",
    legendFlat: "Flat",
    clickHint: "Click any sector to see its top holdings · Updated every 30 minutes",
    sectorCol: "Sector",
    priceCol: "Price",
    changeCol: "Change %",
    inflowCol: "Net Inflow (B)",
    actionCol: "Action",
    viewDetail: "View detail",
    noData: "No data available",
    sectorHistory: "90-Day Trend",
    topHoldings: "Top 5 Holdings",
    chatTitle: "AI Financial Analysis",
    chatPrompt: "Ask me anything about a company's financials",
    chatHint: "I'll pull the latest data and tell you in 30 seconds whether the company is worth your attention.",
    chatPlaceholder: "e.g. Analyze Apple's 2024 financials",
    sectorChatPrompt: "Ask me what is moving this sector",
    sectorChatHint: "I'll map the move, likely drivers, key companies, and what remains uncertain.",
    sectorChatPlaceholder: "e.g. Analyze Technology / 科技 (XLK) and the key companies driving this move",
    loadingMsg: "Analyzing... fetching financial data + AI interpretation, may take 15-30 seconds",
    errorTitle: "Analysis failed",
    errorHint: "Please verify your API key or try again later.",
    identified: "Identified",
    aiDetail: "Detailed AI analysis",
    sectorAiDetail: "Sector radar readout",
    sectorRadarEyebrow: "Sector Radar",
    sectorRadarTitle: "Sector move detected",
    sectorRadarSubtitle: "A board-level read of the theme: what moved, who is driving it, and where uncertainty still lives.",
    sectorRadarMode: "Sector mode",
    sectorRadarMove: "Move",
    sectorRadarMoveBody: "What changed in the sector and why the market is paying attention.",
    sectorRadarCompanies: "Drivers",
    sectorRadarCompaniesBody: "Representative companies likely shaping the move.",
    sectorRadarUnknowns: "Unknowns",
    sectorRadarUnknownsBody: "What the current signal still cannot prove.",
    settingsBtn: "Configured",
    settingsBtnEmpty: "Configure AI",
    chatFloatingTitle: "Ask AI",
    chatExpand: "Expand",
    chatCollapse: "Collapse",
    analysisIntroEyebrow: "AI financial analysis workspace",
    analysisIntroTitle: "From public filings to a readable risk report.",
    analysisIntroBody: "This page turns a company question into a structured financial diagnosis: risk-control methods first, model evidence second, and AI explanation only after the data has been checked.",
    analysisIntroSectorTitle: "Read a sector move like an analyst.",
    analysisIntroSectorBody: "Ask about a market theme or sector, and the workspace separates price action, likely drivers, representative companies, and what the current signal still cannot prove.",
    analysisIntroRiskTitle: "Risk-control methods",
    analysisIntroRiskBody: "The engine combines classic models with statement cross-checks, so risk is not reduced to a single ratio.",
    analysisIntroRiskItem1: "Altman Z-Score, Beneish M-Score, cash-flow quality, and receivables pressure.",
    analysisIntroRiskItem2: "Eight statement scenarios: revenue, inventory, fixed assets, hidden debt, goodwill, liquidity, margins, and cash conversion.",
    analysisIntroRiskItem3: "Disclosure-note review prompts for items the structured statements cannot fully prove.",
    analysisIntroMethodTitle: "Verification logic",
    analysisIntroMethodBody: "The workflow looks for places where the income statement, balance sheet, and cash-flow statement stop explaining each other.",
    analysisIntroMethodItem1: "Compares growth, balances, turnover, margin, leverage, and cash-flow conversion.",
    analysisIntroMethodItem2: "Names missing evidence instead of filling gaps with confident guesses.",
    analysisIntroMethodItem3: "Keeps valuation, financial quality, and risk signals separated before summarizing.",
    analysisIntroOutputTitle: "Output mode",
    analysisIntroOutputBody: "The result is designed for reading, not a tiny chat bubble: a full-page report with risk cards, disclosure checks, and narrative analysis.",
    analysisIntroOutputItem1: "Risk dashboard with red flags and scenario-level evidence.",
    analysisIntroOutputItem2: "Company identification, market, fiscal year, and analysis scope.",
    analysisIntroOutputItem3: "Markdown report that explains what the data supports and what remains uncertain.",
    analysisIntroFlow1: "Identify the target",
    analysisIntroFlow1Body: "Natural language is mapped to ticker, market, fiscal period, and requested analysis type.",
    analysisIntroFlow2: "Run the checks",
    analysisIntroFlow2Body: "Structured financial data is scored before the LLM writes any conclusion.",
    analysisIntroFlow3: "Read the full page",
    analysisIntroFlow3Body: "The report expands into the page so you can scan risks, evidence, and narrative without a modal.",
    analysisBackToIntro: "Back to overview",
    portfolioIntroEyebrow: "Portfolio diagnostic workspace",
    portfolioIntroTitle: "See concentration before it becomes portfolio risk.",
    portfolioIntroBody: "Enter holdings and weights, then get a full-page diagnosis of weighted risk, sector concentration, market exposure, and single-name signals.",
    portfolioIntroRiskTitle: "Weighted risk",
    portfolioIntroRiskBody: "Each holding contributes to portfolio risk according to its weight, so large positions are treated as large exposures.",
    portfolioIntroExposureTitle: "Exposure map",
    portfolioIntroExposureBody: "Sector and market distribution show where the portfolio is concentrated and where diversification may be thinner than it looks.",
    portfolioIntroOutputTitle: "Output mode",
    portfolioIntroOutputBody: "The result expands into a report with score, warnings, charts, holdings detail, and missing-data notes.",
    portfolioIntroFlow1: "Add tickers and position sizes",
    portfolioIntroFlow2: "Run weighted risk and concentration checks",
    portfolioIntroFlow3: "Read the full portfolio diagnosis",
    portfolioIntroExampleLabel: "Example exposure view",
    portfolioIntroPieCenter: "Portfolio",
    portfolioIntroExampleTech: "Technology 42%",
    portfolioIntroExampleConsumer: "Consumer 26%",
    portfolioIntroExampleCashflow: "Cash-flow compounders 16%",
    portfolioIntroExampleRisk: "High-risk names 16%",
    portfolioIntroExampleBody: "The pie chart is the core view: it turns a list of tickers into visible concentration, so users can immediately see whether one sector or theme dominates the portfolio.",
    compareIntroEyebrow: "Multi-company comparison workspace",
    compareIntroTitle: "Put peer companies on the same financial grid.",
    compareIntroBody: "Compare two to four companies across valuation, profitability, balance sheet strength, cash flow, and risk dimensions.",
    compareIntroPeerTitle: "Peer set",
    compareIntroPeerBody: "Add comparable tickers and keep them side by side instead of switching between separate reports.",
    compareIntroMetricTitle: "Comparable metrics",
    compareIntroMetricBody: "The table highlights financial, valuation, cash-flow, and risk differences using the same period and consistent formatting.",
    compareIntroOutputTitle: "Output mode",
    compareIntroOutputBody: "The result is a full-page comparison report with export support and clear best-value markings.",
    compareIntroFlow1: "Choose 2-4 companies",
    compareIntroFlow2: "Fetch financials and risk scores",
    compareIntroFlow3: "Review the full comparison page",
    compareIntroExampleLabel: "Example comparison grid",
    compareIntroExampleA: "Company A",
    compareIntroExampleB: "Company B",
    compareIntroExampleC: "Company C",
    compareIntroExampleMetric1: "Risk score",
    compareIntroExampleMetric2: "Cash-flow quality",
    compareIntroExampleMetric3: "Valuation multiple",
    compareIntroExampleBody: "The special value is visual comparison: scores, bars, and best-value markers let users see outliers faster than reading separate reports.",
    dcfIntroEyebrow: "Valuation workspace",
    dcfIntroTitle: "Build the right valuation framework before trusting the number.",
    dcfIntroBody: "Run a classic DCF, then let the workspace classify the company, expose the right drivers, calculate editable SOTP scenarios, and show what the market price is implicitly assuming.",
    dcfIntroModelTitle: "Framework first",
    dcfIntroModelBody: "The workspace identifies whether a company is a stable FCF compounder, software platform, bank, REIT, pharma pipeline, commodity business, or optionality story.",
    dcfIntroDriverTitle: "Executable drivers",
    dcfIntroDriverBody: "For supported templates, drivers are real inputs. Tesla can be modeled through Auto, Energy, FSD subscription, and Robotaxi assumptions instead of one growth slider.",
    dcfIntroMarketTitle: "Market-implied view",
    dcfIntroMarketBody: "The model back-solves what the current share price must believe: required FCF growth, terminal growth, valuation premium, and optionality gap.",
    dcfIntroContextTitle: "Valuation context",
    dcfIntroContextBody: "Forward P/E, PEG, EV/Sales, implied growth, margin trends, and analyst targets sit beside the DCF output.",
    dcfIntroOutputTitle: "Output mode",
    dcfIntroOutputBody: "The result opens as a full-page valuation report with scenario sensitivity and disagreement signals.",
    dcfIntroFlow1: "Resolve ticker and select framework",
    dcfIntroFlow2: "Run DCF plus editable drivers",
    dcfIntroFlow3: "Read market-implied assumptions",
    dcfIntroExampleLabel: "Example workflow",
    dcfIntroExampleStep1: "Classify",
    dcfIntroExampleStep2: "Model",
    dcfIntroExampleStep3: "Reverse",
    dcfIntroExampleOutput: "What users get",
    dcfIntroFormulaBody: "Start with DCF, then add the valuation framework layer: company type, recommended methods, editable drivers, and market-implied assumptions.",
    dcfIntroWaccTitle: "Example WACC build",
    dcfIntroTeslaTitle: "Tesla example: from DCF to drivers",
    dcfIntroTeslaAuto: "Vehicle delivery, ASP, margin",
    dcfIntroTeslaEnergy: "Storage revenue and margin",
    dcfIntroTeslaFsd: "Fleet, attach rate, ARPU",
    dcfIntroTeslaRobotaxi: "TAM, share, probability",
    dcfIntroSourceTreasury: "Source: 10-year Treasury yield used as the risk-free rate.",
    dcfIntroSourceMarket: "Source: market beta and company trading data.",
    dcfIntroSourceAdjusted: "Adjusted beta smooths extreme market sensitivity.",
    dcfIntroSourceAssumption: "Equity risk premium is the market return assumption above the risk-free rate.",
    dcfIntroExampleBody: "For Tesla, the gap between DCF and market price becomes a question: how much value must come from FSD, Robotaxi, Energy, or other optionality?",
    riskLow: "Low Risk",
    riskMedium: "Medium Risk",
    riskHigh: "High Risk",
    riskLevel_low: "Low Risk",
    riskLevel_medium_low: "Medium-Low Risk",
    riskLevel_medium: "Medium Risk",
    riskLevel_medium_high: "Medium-High Risk",
    riskLevel_high: "High Risk",
    riskScoreLabel: "Risk score / 100",
    modelConfidenceTitle: "Model confidence",
    confidence_high: "High confidence",
    confidence_medium: "Medium confidence",
    confidence_low: "Low confidence",
    riskDriversTitle: "Key risk drivers",
    riskMitigantsTitle: "Mitigating factors",
    stressTestsTitle: "Stress tests",
    requestedPeriod: "Requested year",
    actualFiscalYear: "Actual fiscal year",
    dataSource: "Data source",
    staleData: "Stale cache",
    periodMismatch: "Year mismatch",
    riskBasedOn: "Based on Altman Z-Score, Beneish M-Score, cash flow quality, and eight statement cross-check scenarios",
    riskBasedOnZDoublePrime: "Based on Altman Z'', Beneish M-Score, cash flow quality, and eight statement cross-check scenarios",
    riskBasedOnNoAltman: "Based on sector-specific liquidity, leverage, asset-quality, cash-flow, and statement cross-check scenarios",
    industryModelTitle: "Industry-aware model selection",
    industryProfileLabel: "Profile",
    industryModelLabel: "Risk model",
    industryConfidenceLabel: "Confidence",
    industryModelOriginalNote: "Original Altman Z-Score is used because this company looks closer to a manufacturing or asset-turnover business.",
    industryModelZDoublePrimeNote: "Altman Z'' is used because it removes Sales / Total Assets, reducing asset-turnover bias for non-manufacturing companies.",
    industryModelNotApplicableNote: "Altman Z-Score is not suitable for this business model, so the read relies on sector-specific liquidity, leverage, asset-quality, and cash-flow checks.",
    industryProfile_bank_or_financial: "Bank / financial institution",
    industryProfile_insurance: "Insurance",
    industryProfile_reit: "REIT / real estate trust",
    industryProfile_manufacturing: "Manufacturing / asset turnover",
    industryProfile_tech_light_asset: "Technology / light-asset",
    industryProfile_retail: "Retail",
    industryProfile_energy_or_capital_intensive: "Energy / capital intensive",
    industryProfile_generic_non_manufacturing: "Generic non-manufacturing",
    industryProfile_unknown: "Unknown",
    riskModel_financial_institution_framework: "Financial institution framework",
    riskModel_insurance_framework: "Insurance framework",
    riskModel_reit_framework: "REIT framework",
    riskModel_altman_original_plus_quality_checks: "Original Altman + quality checks",
    riskModel_z_double_prime_plus_cash_quality: "Altman Z'' + cash quality",
    riskModel_z_double_prime_plus_inventory_cash_conversion: "Altman Z'' + inventory/cash conversion",
    riskModel_z_double_prime_plus_debt_capex_coverage: "Altman Z'' + debt/capex coverage",
    riskModel_z_double_prime_plus_quality_checks: "Altman Z'' + quality checks",
    redFlagsTitle: "{n} signals to watch",
    riskScenarioTitle: "Statement Risk Scenarios",
    riskScenarioSubtitle: "Eight cross-checks across the income statement, balance sheet, cash flow statement, and disclosure notes.",
    riskDisclosureChecks: "Disclosure checks",
    riskMissingData: "Missing data",
    riskNoMissingData: "Structured statements cover the main automated checks.",
    radarTitle: "5-Dimension Health",
    radarSubtitle: "Each dimension scored 0-100, higher is healthier",
    dimProfitability: "Profitability",
    dimSolvency: "Solvency",
    dimCashFlow: "Cash Flow",
    dimRevenueQuality: "Revenue Quality",
    dimValuation: "Valuation",
    metricAltman: "Altman Z-Score",
    metricAltmanSub: "Bankruptcy risk prediction",
    metricAltmanZDoublePrimeSub: "Non-manufacturing bankruptcy-risk screen",
    metricBeneish: "Beneish M-Score",
    metricBeneishSub: "Earnings manipulation detection",
    metricCash: "Cash Flow Match",
    metricCashSub: "Earnings quality",
    metricAR: "AR Growth Rate",
    metricARSub: "Revenue authenticity",
    settingsTitle: "Settings",
    settingsAi: "AI Provider",
    settingsApiKey: "API Key",
    settingsTheme: "Theme",
    settingsLanguage: "Language",
    settingsMarket: "Default Market",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    keyHint: "Your key is stored only in your browser, never uploaded.",
    cancel: "Cancel",
    save: "Save",
    compareTitle: "Compare Companies",
    compareSubtitle: "Side-by-side comparison of 2-4 companies, Apple-style",
    compareHeaderSubtitle: "Add 2-4 tickers to compare side-by-side",
    compareTickerPlaceholder: "e.g. AAPL, MSFT, GOOGL, 600519...",
    compareAdd: "Add",
    compareRun: "Compare",
    compareNeed2: "Need at least 2 companies",
    compareMax4: "Max 4 companies",
    compareAlready: "Already added",
    compareExportPDF: "Export PDF",
    compareRiskScore: "Risk Score",
    compareDimensions: "5-Dimension Health",
    compareDimHint: "Higher is healthier",
    compareGroupOverview: "Financial Overview",
    compareGroupProfit: "Profitability",
    compareGroupBalance: "Balance Sheet",
    compareGroupCashflow: "Cash Flow",
    compareBestValue: "Best value among compared",
    comparePeriod: "Period",
    compareFailed: "Failed to compare",
    exportPdf: "Export PDF",
    exportPdfReport: "Export PDF Report",
    tickerRequired: "Ticker is required",
    portfolioTitle: "My Portfolio",
    portfolioSubtitle: "Diagnose your holdings — weighted risk, sector concentration, individual signals. Stored locally.",
    portfolioHeaderTitle: "My Portfolio · AI Diagnosis",
    portfolioHeaderSubtitle: "Enter your holdings to get a weighted risk diagnosis. Stored locally in your browser.",
    portfolioTickerPh: "Ticker (AAPL, 600519, 00700...)",
    portfolioAmountPh: "Position size ($, optional)",
    portfolioAdd: "Add",
    portfolioMax: "Max 15 holdings",
    portfolioClearAll: "Clear all",
    portfolioTotal: "Total",
    portfolioDiagnose: "Diagnose My Portfolio",
    portfolioAnalyzing: "Analyzing portfolio...",
    portfolioNeedHolding: "Add at least one holding",
    portfolioWeightedRisk: "Portfolio Risk / 100",
    portfolioSummaryDisclaimer: "Diagnostic only — not investment advice.",
    portfolioSignals: "Individual Stock Signals",
    portfolioSectorConcentration: "Sector Concentration",
    portfolioGeoDistribution: "Geographic Distribution",
    portfolioHoldings: "Holdings Detail",
    portfolioRemoveConfirm: "Remove all holdings?",
    portfolioDiagnosisFailed: "Diagnosis failed",
    portfolioPublicDataDisclaimer: "Diagnostic only — not investment advice. All conclusions are based on public financial data.",
    portfolioSomeDataMissing: "Some data couldn't be loaded:",
    portfolioTickerCol: "Ticker",
    portfolioNameCol: "Name",
    portfolioSectorCol: "Sector",
    portfolioWeightCol: "Weight",
    dcfTitle: "DCF Valuation",
    dcfHeaderTitle: "Model Builder · DCF Valuation",
    dcfSubtitle: "Two-stage DCF valuation with WACC build-up, net debt adjustment, and implied growth",
    dcfTicker: "Ticker",
    dcfTickerPlaceholder: "AAPL, Tesla, TSLA...",
    dcfSymbolSearching: "Searching ticker matches...",
    dcfSymbolMatches: "Possible matches",
    dcfSymbolSelected: "Using {symbol} - {name}.",
    dcfSymbolAutoResolved: "Recognized {input} as {symbol} - {name}.",
    dcfSymbolNeedsChoice: "Multiple ticker matches found. Choose one before running DCF.",
    valuationFrameworkEyebrow: "Valuation framework",
    valuationFrameworkConfidence: "Fit",
    valuationFrameworkMethods: "Recommended methods",
    valuationFrameworkPrinciple: "Principle:",
    valuationRole_primary: "primary",
    "valuationRole_cross-check": "cross-check",
    valuationRole_diagnostic: "diagnostic",
    valuationRole_supplemental: "supplemental",
    valuationDriverTemplateTitle: "Driver template",
    valuationDriverInputs: "Inputs",
    valuationDriverOutputs: "Outputs",
    valuationMarketImpliedTitle: "Market-implied assumption questions",
    marketImpliedEyebrow: "Phase 3",
    marketImpliedTitle: "Market Implied Assumptions",
    marketImpliedSubtitle: "This does not say the market is right. It shows what the current price must believe under this model structure.",
    marketImpliedBaseline: "Current assumption",
    marketImpliedStatus_reasonable: "reasonable",
    marketImpliedStatus_stretched: "stretched",
    marketImpliedStatus_extreme: "extreme",
    marketImpliedStatus_unknown: "unknown",
    driverValuationEyebrow: "Executable drivers",
    driverValuationTitle: "Editable Driver Valuation",
    driverValuationSubtitle: "Adjust the assumptions directly. The model recalculates segment revenue, profit, value, and per-share SOTP value.",
    driverUnsupported: "This driver model is not executable for this ticker yet.",
    driverLoadFailed: "Failed to load driver assumptions.",
    driverCalcFailed: "Failed to calculate driver valuation.",
    driverValuePerShare: "SOTP value / share",
    driverMarketGap: "Market gap",
    driverSegmentValue: "Segment value",
    driverRevenue: "Revenue",
    driverProfit: "Profit",
    dcfWacc: "Discount Rate (WACC)",
    dcfWaccLoading: "Calculating suggested WACC...",
    dcfWaccSuggested: "Suggested by CAPM + capital structure",
    dcfWaccHint: "Higher = more conservative",
    dcfGrowth: "Stage 1 FCF Growth (5y)",
    dcfGrowthHint: "Annual FCF growth assumption",
    dcfGrowthTooltipTitle: "How we estimate growth",
    dcfGrowthTooltipBody: "The default uses recent earnings growth first, then revenue growth if earnings growth is unavailable. For high-growth technology companies, the cap rises to 45%; otherwise it is capped at 25%. If live data is missing, we fall back to 5%.",
    dcfGrowthTooltipCaution: "This is a scenario input, not a forecast. Change it when your view of future cash-flow growth differs from recent fundamentals.",
    dcfTerminal: "Terminal Growth",
    dcfTerminalHint: "Long-term GDP-like growth",
    dcfTerminalTooltipTitle: "Why GDP-like growth",
    dcfTerminalTooltipBody: "Terminal growth represents the steady-state growth rate after the explicit forecast period. We default to 2.5% because a mature company should not outgrow the economy forever.",
    dcfTerminalTooltipCaution: "Keep terminal growth below WACC. Small changes here can move valuation sharply because it drives the terminal value.",
    dcfRun: "Run DCF Valuation",
    dcfRunning: "Calculating...",
    dcfIntrinsic: "Intrinsic Value",
    dcfIntrinsicSub: "per share",
    dcfCurrent: "Current Price",
    dcfCurrentSub: "market price",
    dcfUpside: "Upside / Downside",
    dcfUndervalued: "above market under these inputs",
    dcfOvervalued: "below market under these inputs",
    dcfAssumptionTitle: "Assumption-sensitive result.",
    dcfAssumptionBody: "DCF can be unreliable for hyper-growth stocks; this value reflects {growth}% near-term FCF growth and a {discount}% discount rate.",
    dcfMarketImplies: "Market price implies roughly {implied} Stage 1 growth in this model.",
    dcfCompareImplied: "Compare the implied growth with your own view of the business.",
    dcfFcfProjection: "10-Year Two-Stage FCF Projection (Present Value, $B)",
    dcfYear: "Year",
    dcfFutureFcf: "FCF (Future)",
    dcfPresentValue: "Present Value",
    dcfCurrentFcf: "Current FCF",
    dcfTerminalValuePv: "Terminal Value (PV)",
    dcfEnterpriseValue: "Enterprise Value",
    dcfEquityValue: "Equity Value",
    dcfSharesOut: "Shares Out",
    dcfNetDebt: "Net Debt",
    dcfNetCash: "Net Cash",
    dcfTerminalPct: "Terminal % of EV",
    dcfImpliedGrowth: "Implied Growth",
    dcfSuggestedWacc: "Suggested WACC",
    dcfRiskFree: "Risk-free rate (10Y T)",
    dcfBeta: "Beta",
    dcfRawBeta: "Raw beta",
    dcfEquityRiskPremium: "Equity risk premium",
    dcfCostOfEquity: "Cost of equity",
    dcfCostOfDebt: "Cost of debt (after tax)",
    dcfTaxRate: "Tax rate",
    dcfMarketCapWeight: "Market cap weight",
    dcfDebtWeight: "Debt weight",
    dcfGrowthProfile: "Growth-sensitive default",
    dcfGrowthProfileBody: "For high-growth technology companies, defaults now use recent fundamental growth with a higher growth ceiling and Blume-adjusted beta. Treat it as a starting scenario, not a target price.",
    dcfContextTitle: "Valuation context",
    dcfContextSubtitle: "For high-growth companies, read DCF alongside multiples, growth quality, margins, and market-implied expectations.",
    dcfThreeAnswersTitle: "Three answers, one uncertainty",
    dcfOurDcfAnswer: "Our DCF",
    dcfMarketAnswer: "Market price",
    dcfAnalystAnswer: "Wall St. target",
    dcfAnalystCount: "{n} analysts",
    dcfTargetRange: "Target range",
    dcfRecommendation: "Consensus",
    dcfDisagreementSignal: "These answers can disagree sharply. That disagreement is the signal: DCF, market price, and analyst targets are different lenses, not certain truth.",
    dcfAnalystCaveat: "Analyst targets can be stale or optimistic, so treat them as a second opinion rather than the answer.",
    dcfViewAnalysts: "View analyst coverage",
    dcfAnalystDrawerTitle: "Wall St. coverage",
    dcfAnalystDrawerSubtitle: "Recent yfinance rating actions and target-price consensus. Availability varies by ticker.",
    dcfAnalystFirm: "Firm",
    dcfAnalystAction: "Action",
    dcfAnalystToGrade: "To grade",
    dcfAnalystFromGrade: "From",
    dcfNoAnalystEntries: "No recent firm-level rating actions available from yfinance.",
    dcfHighGrowthWarning: "High-growth profile detected: DCF can become extremely unstable. Treat the intrinsic value as a scenario output, not a verdict.",
    dcfStability: "DCF stability",
    dcfUnstable: "Extremely unstable",
    dcfModerate: "Moderate",
    dcfForwardPe: "Forward P/E",
    dcfPeg: "PEG",
    dcfEvSales: "EV/Sales",
    dcfEvRevenueGrowth: "EV/Revenue Growth",
    dcfRevenueGrowth: "Revenue Growth",
    dcfEarningsGrowth: "Earnings Growth",
    dcfGrossMargin: "Gross Margin",
    dcfOperatingMargin: "Operating Margin",
    dcfMarginTrend: "Margin trend",
    dcfMarketImplied: "Market-implied Growth",
    dcfContextNote: "No single metric settles valuation. The point is to compare what the market is pricing against growth durability and margin quality.",
    dcfBankWarning: "Banks and financial companies are better valued with Residual Income or P/B models, not classic FCF DCF.",
    dcfReitWarning: "REITs are better valued with FFO/AFFO, not classic FCF DCF.",
    dcfSensitivityTitle: "Sensitivity Analysis · Three Scenarios",
    dcfConservative: "Conservative",
    dcfBase: "Base Case",
    dcfOptimistic: "Optimistic",
    dcfGrowthLabel: "Growth",
    dcfVsMarket: "vs market",
    dcfNotAvailable: "N/A",
    usMarket: "US Stocks",
    cnMarket: "China A-Shares",
    hkMarket: "Hong Kong Stocks",
    footerDisclaimer: "For educational use only. Nothing here constitutes investment advice.",
    backToHome: "Back to home",
    loading: "Loading...",
  },
  zh: {
    brand: "fin-agent-pro",
    navMarketUS: "美股",
    navMarketCN: "A 股",
    navMarketHK: "港股",
    navPortfolio: "投资组合",
    navCompare: "对比",
    navValuation: "估值",
    navAnalysis: "AI 分析",
    navSettings: "设置",
    heroTitle: "fin-agent-pro",
    heroSubtitle: "一个金融分析工作区，把市场背景、公司风险、估值框架、组合诊断和 AI 研究放在一起。",
    heroCTAPrimary: "查看市场",
    heroCTASecondary: "了解更多",
    heroVisualKnownLabel: "可验证信号",
    heroVisualKnownBody: "市场走势、财务报表、风险模型、估值假设和组合暴露——都尽量用公开数据交叉验证。",
    heroVisualUnknownLabel: "不确定性地图",
    heroVisualUnknownBody: "模型边界、缺失数据、滞后目标价、集中度风险和市场隐含假设会被明确标出。",
    heroVisualEyebrow: "一个更清醒的投资研究工作区",
    heroVisualTitle: "看见信号、风险和假设。",
    learnMore: "了解更多",
    tryIt: "立即体验",

    // 首页滚动叙事
    featMarketEyebrow: "大盘指数",
    featMarketTitle: "全球市场，一屏掌握。",
    featMarketBody: "标普 500、纳斯达克、恒生指数——一眼看尽。实时百分比变动 + 自动货币格式化，不用再切换 App 看不同市场。",

    featHeatmapEyebrow: "行业热度图",
    featHeatmapTitle: "热点一目了然。",
    featHeatmapBody: "新闻滞后，交易行为不会。这张图显示资金和波动当前聚集在哪——不是叫你买什么，而是告诉你该往哪看。",

    featAiEyebrow: "AI 财务分析",
    featAiTitle: "30 秒，看懂任何公司。",
    featAiBody: "Altman Z-Score、Beneish M-Score、Claude/GPT-4o 多模型驱动。用大白话提问，得到机构级风险解读和红旗预警——专业严谨，散户友好。",

    featCompareEyebrow: "多公司对比",
    featCompareTitle: "苹果风格的横向对比。",
    featCompareBody: "支持 2-4 家公司在财务、风险、估值维度并排对比。最优项自动高亮——就像苹果官网比较 iPhone 那样直观。",

    featPortfolioEyebrow: "投资组合诊断",
    featPortfolioTitle: "看清你的持仓集中度。",
    featPortfolioBody: "加权风险评分、行业集中度告警、个股红旗。给你的组合做一次全面体检——只诊断，不建议；数据永远不离开你的浏览器。",

    featDcfEyebrow: "估值引擎",
    featDcfTitle: "DCF、drivers 和隐含假设。",
    featDcfBody: "先从 DCF 开始，再进入框架化 drivers。Tesla 可以拆成 Auto、Energy、FSD 和 Robotaxi，并明确展示市场隐含假设。",
    marketOverviewTitle: "市场概览",
    marketOverviewSubtitle: "实时指数、板块脉搏、今日热点。",
    sectorHeatmapTitle: "行业热度地图",
    sectorHeatmapSubtitle: "气泡越大 = 资金越关注 · 颜色越深 = 波动越剧烈",
    heatmapBehaviorMantra: "新闻滞后，交易行为不会。",
    heatmapBehaviorBody: "这张图显示资金和波动当前聚集在哪——不是叫你买什么，而是告诉你该往哪看。",
    sectorRankingTitle: "板块排行",
    hkAnalysisTitle: "分析任何港股公司",
    hkAnalysisBody: "港股暂不支持行业热度图，但你可以让 AI 分析任何港股个股——腾讯 (00700)、汇丰 (00005)、阿里 (09988)、小米 (01810) 等。同样的 Altman Z-Score / Beneish M-Score / 财务全面解读。",
    hkAnalysisCTA: "问 AI",
    dataUnavailableTitle: "市场数据暂时不可用",
    dataUnavailableBody: "数据源（东方财富/AkShare）当前未响应，与你无关。个股 AI 分析仍然可用——可以使用右下角浮动对话框测试。",
    sectorDataUnavailableTitle: "A 股板块数据暂时不可用",
    sectorDataUnavailableBody: "指数行情可以获取，但东方财富的行业板块或资金流接口没有返回可用数据。有缓存时会优先展示旧数据；个股 AI 分析仍然可用。",
    cnFallbackTitle: "分析任何 A 股公司",
    cnFallbackBody: "大盘数据暂不可用，但你仍可以让 AI 分析任何 A 股个股——贵州茅台 (600519)、宁德时代 (300750)、比亚迪 (002594) 等。完整财务解读 + Altman Z-Score + Beneish M-Score。",
    cnFallbackCTA: "问 AI",
    catIndustry: "行业",
    catSize: "市值",
    catRegion: "地域",
    viewHeatmap: "热度图",
    viewRank: "排行",
    todayHottest: "今日最热：",
    legendUp: "上涨",
    legendDown: "下跌",
    legendFlat: "持平",
    clickHint: "点击任何板块查看其领涨公司 · 数据每 30 分钟更新",
    sectorCol: "板块",
    priceCol: "价格",
    changeCol: "涨跌幅",
    inflowCol: "主力净流入(亿)",
    actionCol: "操作",
    viewDetail: "查看详情",
    noData: "暂无数据",
    sectorHistory: "近 90 天走势",
    topHoldings: "前 5 大成分股",
    chatTitle: "AI 财务分析",
    chatPrompt: "问我任何公司的财务问题",
    chatHint: "我会拉取最新财务数据，30 秒内告诉你这家公司值不值得关注",
    chatPlaceholder: "例：分析苹果 2024 年的财务状况",
    sectorChatPrompt: "问我这个板块为什么在动",
    sectorChatHint: "我会梳理板块异动、可能驱动因素、关键公司，以及仍然未知的部分。",
    sectorChatPlaceholder: "例：分析科技板块，以及推动本轮走势的关键公司",
    loadingMsg: "正在分析中... 拉取财务数据 + AI 解读，可能需要 15-30 秒",
    errorTitle: "分析出错",
    errorHint: "请检查 API Key 是否正确，或稍后重试。",
    identified: "已识别",
    aiDetail: "AI 详细解读",
    sectorAiDetail: "板块雷达解读",
    sectorRadarEyebrow: "板块雷达",
    sectorRadarTitle: "检测到板块异动",
    sectorRadarSubtitle: "先看整片天气：发生了什么、谁在驱动、哪些地方仍然看不清。",
    sectorRadarMode: "板块模式",
    sectorRadarMove: "异动",
    sectorRadarMoveBody: "这个板块发生了什么，市场为什么开始重新定价。",
    sectorRadarCompanies: "驱动",
    sectorRadarCompaniesBody: "最可能塑造本轮行情的代表公司。",
    sectorRadarUnknowns: "未知",
    sectorRadarUnknownsBody: "当前信号还无法证明的部分。",
    settingsBtn: "已配置",
    settingsBtnEmpty: "配置 AI",
    chatFloatingTitle: "问 AI",
    chatExpand: "展开",
    chatCollapse: "收起",
    analysisIntroEyebrow: "AI 财务分析工作区",
    analysisIntroTitle: "从公开财报到可阅读的风险报告。",
    analysisIntroBody: "这个页面会把一个公司问题转成结构化财务诊断：先跑风险控制方法，再展示模型证据，最后才让 AI 做解释。",
    analysisIntroSectorTitle: "像分析师一样阅读板块异动。",
    analysisIntroSectorBody: "询问一个市场主题或板块时，工作区会拆出价格异动、可能驱动因素、代表公司，以及当前信号仍然无法证明的部分。",
    analysisIntroRiskTitle: "风险控制方法",
    analysisIntroRiskBody: "引擎结合经典模型和财报交叉验证，不把风险简化成单一比率。",
    analysisIntroRiskItem1: "Altman Z-Score、Beneish M-Score、现金流质量和应收压力。",
    analysisIntroRiskItem2: "八大财报场景：收入、存货、固定资产、隐性债务、商誉、流动性、毛利率和现金转化。",
    analysisIntroRiskItem3: "对结构化三表无法完全证明的部分，给出财报附注核查方向。",
    analysisIntroMethodTitle: "验证逻辑",
    analysisIntroMethodBody: "工作流会寻找利润表、资产负债表和现金流量表之间无法互相解释的地方。",
    analysisIntroMethodItem1: "比较增长、余额、周转、毛利率、杠杆和现金流转化。",
    analysisIntroMethodItem2: "明确标注缺失证据，而不是用自信语气补齐未知。",
    analysisIntroMethodItem3: "先分开呈现估值、财务质量和风险信号，再做总结。",
    analysisIntroOutputTitle: "输出模式",
    analysisIntroOutputBody: "输出不是小聊天窗口，而是适合阅读的整页报告：风险卡片、披露核查和叙事分析并排展开。",
    analysisIntroOutputItem1: "风险仪表盘展示红旗信号和场景级证据。",
    analysisIntroOutputItem2: "展示公司识别、市场、财年和分析范围。",
    analysisIntroOutputItem3: "Markdown 报告说明数据支持什么，以及哪些地方仍然未知。",
    analysisIntroFlow1: "识别对象",
    analysisIntroFlow1Body: "自然语言会被映射为 ticker、市场、财年和分析类型。",
    analysisIntroFlow2: "运行检查",
    analysisIntroFlow2Body: "结构化财务数据先完成评分和交叉验证，然后再进入 AI 解读。",
    analysisIntroFlow3: "整页阅读",
    analysisIntroFlow3Body: "报告会展开成页面内容，方便扫描风险、证据和分析正文。",
    analysisBackToIntro: "返回介绍页",
    portfolioIntroEyebrow: "投资组合诊断工作区",
    portfolioIntroTitle: "在集中度变成组合风险前看见它。",
    portfolioIntroBody: "输入持仓和仓位权重后，系统会生成整页诊断，展示加权风险、行业集中度、市场暴露和单持仓信号。",
    portfolioIntroRiskTitle: "加权风险",
    portfolioIntroRiskBody: "每个持仓按仓位权重贡献组合风险，大仓位会被当作真实的大暴露处理。",
    portfolioIntroExposureTitle: "暴露地图",
    portfolioIntroExposureBody: "行业和市场分布会说明组合集中在哪里，以及表面分散背后的薄弱处。",
    portfolioIntroOutputTitle: "输出模式",
    portfolioIntroOutputBody: "结果会展开成报告，包含评分、警示、图表、持仓明细和缺失数据说明。",
    portfolioIntroFlow1: "添加股票代码和仓位金额",
    portfolioIntroFlow2: "运行加权风险和集中度检查",
    portfolioIntroFlow3: "阅读完整组合诊断",
    portfolioIntroExampleLabel: "示例暴露视图",
    portfolioIntroPieCenter: "组合",
    portfolioIntroExampleTech: "科技 42%",
    portfolioIntroExampleConsumer: "消费 26%",
    portfolioIntroExampleCashflow: "现金流型资产 16%",
    portfolioIntroExampleRisk: "高风险持仓 16%",
    portfolioIntroExampleBody: "饼状图是这个功能的核心视图：它会把 ticker 列表变成可见的集中度，让用户立刻看出组合是否被某个行业或主题主导。",
    compareIntroEyebrow: "多公司对比工作区",
    compareIntroTitle: "把同行公司放到同一张财务网格里。",
    compareIntroBody: "支持 2 到 4 家公司，横向比较估值、盈利能力、资产负债、现金流和风险维度。",
    compareIntroPeerTitle: "同行集合",
    compareIntroPeerBody: "添加可比公司后并排查看，不需要在多份报告之间来回切换。",
    compareIntroMetricTitle: "可比指标",
    compareIntroMetricBody: "用同一财年和统一格式展示财务、估值、现金流和风险差异。",
    compareIntroOutputTitle: "输出模式",
    compareIntroOutputBody: "结果会展开为整页对比报告，支持导出，并清楚标记相对更优项。",
    compareIntroFlow1: "选择 2-4 家公司",
    compareIntroFlow2: "拉取财务数据和风险评分",
    compareIntroFlow3: "阅读完整对比页面",
    compareIntroExampleLabel: "示例对比网格",
    compareIntroExampleA: "公司 A",
    compareIntroExampleB: "公司 B",
    compareIntroExampleC: "公司 C",
    compareIntroExampleMetric1: "风险评分",
    compareIntroExampleMetric2: "现金流质量",
    compareIntroExampleMetric3: "估值倍数",
    compareIntroExampleBody: "它最特别的地方是直观对比：评分、横条和相对更优标记能让用户比阅读多份报告更快发现异常值。",
    dcfIntroEyebrow: "估值工作区",
    dcfIntroTitle: "先选对估值框架，再相信那个数字。",
    dcfIntroBody: "先运行经典 DCF，再让工作区识别公司类型、展示关键 drivers、计算可编辑 SOTP 情景，并反推市场价格到底隐含了什么。",
    dcfIntroModelTitle: "框架优先",
    dcfIntroModelBody: "工作区会判断公司更像稳定现金流复利、软件平台、银行、REIT、药企管线、大宗商品，还是期权型增长故事。",
    dcfIntroDriverTitle: "可计算 Drivers",
    dcfIntroDriverBody: "对已支持的模板，driver 是真实输入。Tesla 可以拆成 Auto、Energy、FSD 订阅和 Robotaxi，而不是只靠一个增长率滑块。",
    dcfIntroMarketTitle: "市场隐含视角",
    dcfIntroMarketBody: "模型会反推当前股价必须相信什么：所需 FCF 增速、终值增长率、估值溢价和期权价值缺口。",
    dcfIntroContextTitle: "估值上下文",
    dcfIntroContextBody: "Forward P/E、PEG、EV/Sales、隐含增长、利润率趋势和分析师目标价会与 DCF 同屏展示。",
    dcfIntroOutputTitle: "输出模式",
    dcfIntroOutputBody: "结果会展开为整页估值报告，包含敏感性情景和分歧信号。",
    dcfIntroFlow1: "识别 ticker 和估值框架",
    dcfIntroFlow2: "运行 DCF 与可编辑 drivers",
    dcfIntroFlow3: "阅读市场隐含假设",
    dcfIntroExampleLabel: "示例工作流",
    dcfIntroExampleStep1: "分类",
    dcfIntroExampleStep2: "建模",
    dcfIntroExampleStep3: "反推",
    dcfIntroExampleOutput: "用户得到什么",
    dcfIntroFormulaBody: "先从 DCF 开始，再叠加估值框架层：公司类型、推荐方法、可编辑 drivers 和市场隐含假设。",
    dcfIntroWaccTitle: "示例 WACC 构成",
    dcfIntroTeslaTitle: "Tesla 示例：从 DCF 到 drivers",
    dcfIntroTeslaAuto: "交付量、ASP、毛利率",
    dcfIntroTeslaEnergy: "储能收入和利润率",
    dcfIntroTeslaFsd: "车队、渗透率、ARPU",
    dcfIntroTeslaRobotaxi: "TAM、份额、概率",
    dcfIntroSourceTreasury: "来源：10 年期美债收益率，作为无风险利率。",
    dcfIntroSourceMarket: "来源：市场 Beta 和公司交易数据。",
    dcfIntroSourceAdjusted: "调整后 Beta 用于平滑过高或过低的市场敏感度。",
    dcfIntroSourceAssumption: "股权风险溢价是高于无风险利率的市场回报假设。",
    dcfIntroExampleBody: "以 Tesla 为例，DCF 与市场价的差距会变成一个问题：多少价值必须来自 FSD、Robotaxi、Energy 或其他期权？",
    riskLow: "低风险",
    riskMedium: "中等风险",
    riskHigh: "高风险",
    riskLevel_low: "低风险",
    riskLevel_medium_low: "中低风险",
    riskLevel_medium: "中等风险",
    riskLevel_medium_high: "中高风险",
    riskLevel_high: "高风险",
    riskScoreLabel: "风险分 / 100",
    modelConfidenceTitle: "模型置信度",
    confidence_high: "高置信度",
    confidence_medium: "中置信度",
    confidence_low: "低置信度",
    riskDriversTitle: "关键风险驱动",
    riskMitigantsTitle: "风险缓释因素",
    stressTestsTitle: "压力测试",
    requestedPeriod: "请求年份",
    actualFiscalYear: "实际使用财年",
    dataSource: "数据源",
    staleData: "旧缓存",
    periodMismatch: "年份不匹配",
    riskBasedOn: "基于 Altman Z-Score、Beneish M-Score、现金流质量和八大财报交叉验证场景评估",
    riskBasedOnZDoublePrime: "基于 Altman Z''、Beneish M-Score、现金流质量和八大财报交叉验证场景评估",
    riskBasedOnNoAltman: "基于行业特定的流动性、杠杆、资产质量、现金流和财报交叉验证场景评估",
    industryModelTitle: "行业适配模型选择",
    industryProfileLabel: "行业画像",
    industryModelLabel: "风险模型",
    industryConfidenceLabel: "置信度",
    industryModelOriginalNote: "该公司更接近制造业或资产周转型业务，因此使用原版 Altman Z-Score。",
    industryModelZDoublePrimeNote: "该公司属于非制造业或轻资产场景，因此使用去掉 Sales / Total Assets 的 Altman Z''，降低资产周转率偏差。",
    industryModelNotApplicableNote: "Altman Z-Score 不适合该商业模式，本页改用行业特定的流动性、杠杆、资产质量和现金流核查。",
    industryProfile_bank_or_financial: "银行 / 金融机构",
    industryProfile_insurance: "保险",
    industryProfile_reit: "REIT / 房地产信托",
    industryProfile_manufacturing: "制造业 / 资产周转型",
    industryProfile_tech_light_asset: "科技 / 轻资产",
    industryProfile_retail: "零售",
    industryProfile_energy_or_capital_intensive: "能源 / 资本密集",
    industryProfile_generic_non_manufacturing: "通用非制造业",
    industryProfile_unknown: "未知",
    riskModel_financial_institution_framework: "金融机构风险框架",
    riskModel_insurance_framework: "保险风险框架",
    riskModel_reit_framework: "REIT 风险框架",
    riskModel_altman_original_plus_quality_checks: "原版 Altman + 质量核查",
    riskModel_z_double_prime_plus_cash_quality: "Altman Z'' + 现金流质量",
    riskModel_z_double_prime_plus_inventory_cash_conversion: "Altman Z'' + 存货/现金转化",
    riskModel_z_double_prime_plus_debt_capex_coverage: "Altman Z'' + 债务/资本开支覆盖",
    riskModel_z_double_prime_plus_quality_checks: "Altman Z'' + 质量核查",
    redFlagsTitle: "发现 {n} 项关注信号",
    riskScenarioTitle: "财报风险场景",
    riskScenarioSubtitle: "覆盖利润表、资产负债表、现金流量表与附注披露的八大交叉验证。",
    riskDisclosureChecks: "披露核查",
    riskMissingData: "缺失信息",
    riskNoMissingData: "结构化三表数据已覆盖主要自动核查项。",
    radarTitle: "五维度健康度",
    radarSubtitle: "每个维度 0-100 分，越大越健康",
    dimProfitability: "盈利能力",
    dimSolvency: "偿债能力",
    dimCashFlow: "现金流",
    dimRevenueQuality: "营收质量",
    dimValuation: "估值",
    metricAltman: "Altman Z-Score",
    metricAltmanSub: "破产风险预测",
    metricAltmanZDoublePrimeSub: "非制造业破产风险筛查",
    metricBeneish: "Beneish M-Score",
    metricBeneishSub: "盈余操纵识别",
    metricCash: "现金流匹配度",
    metricCashSub: "盈利质量",
    metricAR: "应收账款增速",
    metricARSub: "营收真实性",
    settingsTitle: "设置",
    settingsAi: "AI 服务",
    settingsApiKey: "API Key",
    settingsTheme: "主题",
    settingsLanguage: "语言",
    settingsMarket: "默认市场",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    keyHint: "Key 只存于你的浏览器，不会上传任何服务器",
    cancel: "取消",
    save: "保存",
    compareTitle: "多公司对比",
    compareSubtitle: "Apple 风格的横向对比，支持 2-4 家公司",
    compareHeaderSubtitle: "添加 2-4 个股票代码进行横向对比",
    compareTickerPlaceholder: "例：AAPL、MSFT、GOOGL、600519...",
    compareAdd: "添加",
    compareRun: "对比",
    compareNeed2: "至少需要 2 家公司",
    compareMax4: "最多 4 家",
    compareAlready: "已经添加过了",
    compareExportPDF: "导出 PDF",
    compareRiskScore: "风险评分",
    compareDimensions: "五维度健康度",
    compareDimHint: "越高越健康",
    compareGroupOverview: "财务概览",
    compareGroupProfit: "盈利能力",
    compareGroupBalance: "资产负债",
    compareGroupCashflow: "现金流",
    compareBestValue: "对比中最优",
    comparePeriod: "财年",
    compareFailed: "对比失败",
    exportPdf: "导出 PDF",
    exportPdfReport: "导出 PDF 报告",
    tickerRequired: "请输入股票代码",
    portfolioTitle: "我的投资组合",
    portfolioSubtitle: "诊断你的持仓——加权风险、行业集中度、个股信号。数据本地存储。",
    portfolioHeaderTitle: "我的投资组合 · AI 诊断",
    portfolioHeaderSubtitle: "输入持仓后获得加权风险诊断。数据只保存在你的浏览器里。",
    portfolioTickerPh: "代码（AAPL、600519、00700...）",
    portfolioAmountPh: "仓位金额（$，可选）",
    portfolioAdd: "添加",
    portfolioMax: "最多 15 只",
    portfolioClearAll: "全部清空",
    portfolioTotal: "总计",
    portfolioDiagnose: "AI 诊断我的组合",
    portfolioAnalyzing: "正在诊断...",
    portfolioNeedHolding: "请至少添加一只持仓",
    portfolioWeightedRisk: "组合风险 / 100",
    portfolioSummaryDisclaimer: "仅作诊断参考——不构成投资建议。",
    portfolioSignals: "个股信号",
    portfolioSectorConcentration: "行业集中度",
    portfolioGeoDistribution: "地域分布",
    portfolioHoldings: "持仓明细",
    portfolioRemoveConfirm: "确认清空全部持仓？",
    portfolioDiagnosisFailed: "诊断失败",
    portfolioPublicDataDisclaimer: "仅作诊断参考——不构成投资建议。所有结论基于公开财务数据。",
    portfolioSomeDataMissing: "部分数据未能加载：",
    portfolioTickerCol: "代码",
    portfolioNameCol: "名称",
    portfolioSectorCol: "行业",
    portfolioWeightCol: "权重",
    dcfTitle: "DCF 估值",
    dcfHeaderTitle: "模型构建器 · DCF 估值",
    dcfSubtitle: "两阶段 DCF：包含 WACC、净负债调整、终值和隐含增长率",
    dcfTicker: "股票代码",
    dcfTickerPlaceholder: "AAPL、特斯拉、TSLA...",
    dcfSymbolSearching: "正在识别股票代码...",
    dcfSymbolMatches: "可能匹配",
    dcfSymbolSelected: "已使用 {symbol} - {name}。",
    dcfSymbolAutoResolved: "已将 {input} 识别为 {symbol} - {name}。",
    dcfSymbolNeedsChoice: "找到多个可能的股票代码，请先选择一个再运行 DCF。",
    valuationFrameworkEyebrow: "估值框架",
    valuationFrameworkConfidence: "匹配度",
    valuationFrameworkMethods: "推荐估值方法",
    valuationFrameworkPrinciple: "原则：",
    valuationRole_primary: "主模型",
    "valuationRole_cross-check": "交叉验证",
    valuationRole_diagnostic: "诊断",
    valuationRole_supplemental: "补充",
    valuationDriverTemplateTitle: "Driver 模板",
    valuationDriverInputs: "输入假设",
    valuationDriverOutputs: "输出指标",
    valuationMarketImpliedTitle: "市场隐含假设问题",
    marketImpliedEyebrow: "第三阶段",
    marketImpliedTitle: "市场隐含假设",
    marketImpliedSubtitle: "这不是说市场一定正确，而是展示在当前模型结构下，市场价格必须相信什么。",
    marketImpliedBaseline: "当前假设",
    marketImpliedStatus_reasonable: "合理",
    marketImpliedStatus_stretched: "偏激进",
    marketImpliedStatus_extreme: "极端",
    marketImpliedStatus_unknown: "未知",
    driverValuationEyebrow: "可计算 Drivers",
    driverValuationTitle: "可编辑 Driver 估值",
    driverValuationSubtitle: "直接调整假设，模型会重新计算分部收入、利润、价值和每股 SOTP 价值。",
    driverUnsupported: "这个股票的 driver 模型暂时还没有接入真实计算。",
    driverLoadFailed: "加载 driver 假设失败。",
    driverCalcFailed: "计算 driver 估值失败。",
    driverValuePerShare: "SOTP 每股价值",
    driverMarketGap: "市场差额",
    driverSegmentValue: "分部价值",
    driverRevenue: "收入",
    driverProfit: "利润",
    dcfWacc: "折现率 (WACC)",
    dcfWaccLoading: "正在计算建议 WACC...",
    dcfWaccSuggested: "由 CAPM + 资本结构估算",
    dcfWaccHint: "越高越保守",
    dcfGrowth: "第一阶段自由现金流增速 (5 年)",
    dcfGrowthHint: "年化增速假设",
    dcfGrowthTooltipTitle: "我们如何推测增速",
    dcfGrowthTooltipBody: "默认优先使用近期 earnings growth；如果没有，就使用 revenue growth。高增长科技公司上限放宽到 45%；其他公司上限为 25%。如果实时数据缺失，则回退到 5%。",
    dcfGrowthTooltipCaution: "这是场景输入，不是预测结论。如果你对未来现金流增速的判断不同，可以手动调整。",
    dcfTerminal: "终值增长率",
    dcfTerminalHint: "长期 GDP 类增长",
    dcfTerminalTooltipTitle: "为什么用 GDP 类增长",
    dcfTerminalTooltipBody: "终值增长率代表明确预测期之后的稳定增长。默认 2.5%，因为成熟公司不应该被假设为永远跑赢整个经济。",
    dcfTerminalTooltipCaution: "终值增长率必须低于 WACC。它会影响终值，哪怕小幅变化也可能显著改变估值。",
    dcfRun: "运行 DCF",
    dcfRunning: "计算中...",
    dcfIntrinsic: "内在价值",
    dcfIntrinsicSub: "每股",
    dcfCurrent: "当前价格",
    dcfCurrentSub: "市场价",
    dcfUpside: "上涨 / 下跌空间",
    dcfUndervalued: "在这些假设下高于市场价",
    dcfOvervalued: "在这些假设下低于市场价",
    dcfAssumptionTitle: "结果对假设高度敏感。",
    dcfAssumptionBody: "DCF 对高增长股票并不稳定；这个估值使用了 {growth}% 近期自由现金流增速和 {discount}% 折现率。",
    dcfMarketImplies: "在这个模型里，市场价格隐含约 {implied} 的第一阶段增长率。",
    dcfCompareImplied: "请把隐含增长率与你对公司的判断放在一起看。",
    dcfFcfProjection: "10 年两阶段自由现金流预测（现值，$B）",
    dcfYear: "年份",
    dcfFutureFcf: "未来 FCF",
    dcfPresentValue: "现值",
    dcfCurrentFcf: "当前 FCF",
    dcfTerminalValuePv: "终值现值",
    dcfEnterpriseValue: "企业价值",
    dcfEquityValue: "股权价值",
    dcfSharesOut: "流通股本",
    dcfNetDebt: "净债务",
    dcfNetCash: "净现金",
    dcfTerminalPct: "终值占 EV",
    dcfImpliedGrowth: "隐含增长率",
    dcfSuggestedWacc: "建议 WACC",
    dcfRiskFree: "无风险利率（10 年期美债）",
    dcfBeta: "调整后 Beta",
    dcfRawBeta: "原始 Beta",
    dcfEquityRiskPremium: "股权风险溢价",
    dcfCostOfEquity: "股权成本",
    dcfCostOfDebt: "债务成本（税后）",
    dcfTaxRate: "税率",
    dcfMarketCapWeight: "市值权重",
    dcfDebtWeight: "债务权重",
    dcfGrowthProfile: "高增长默认假设",
    dcfGrowthProfileBody: "对高增长科技公司，默认值现在会参考近期基本面增长，并使用更高的增长上限和 Blume 调整 Beta。它是起始场景，不是目标价。",
    dcfContextTitle: "估值上下文",
    dcfContextSubtitle: "对高增长公司，要把 DCF 与估值倍数、增长质量、利润率和市场隐含预期放在一起看。",
    dcfThreeAnswersTitle: "三个答案，一个不确定性",
    dcfOurDcfAnswer: "我们的 DCF",
    dcfMarketAnswer: "市场价格",
    dcfAnalystAnswer: "华尔街目标价",
    dcfAnalystCount: "{n} 位分析师",
    dcfTargetRange: "目标价区间",
    dcfRecommendation: "共识评级",
    dcfDisagreementSignal: "这些答案可能剧烈分歧。分歧本身就是信号：DCF、市场价格和机构目标价是三种视角，不是确定真相。",
    dcfAnalystCaveat: "分析师目标价可能滞后或偏乐观，所以它只是第二意见，不是正确答案。",
    dcfViewAnalysts: "查看分析师覆盖",
    dcfAnalystDrawerTitle: "华尔街覆盖记录",
    dcfAnalystDrawerSubtitle: "来自 yfinance 的近期评级动作与目标价共识。不同股票可用字段会不同。",
    dcfAnalystFirm: "机构",
    dcfAnalystAction: "动作",
    dcfAnalystToGrade: "当前评级",
    dcfAnalystFromGrade: "此前评级",
    dcfNoAnalystEntries: "yfinance 暂无近期机构级评级动作。",
    dcfHighGrowthWarning: "检测到高增长特征：DCF 会变得极不稳定。请把内在价值视为情景输出，而不是定论。",
    dcfStability: "DCF 稳定性",
    dcfUnstable: "极不稳定",
    dcfModerate: "中等",
    dcfForwardPe: "Forward P/E",
    dcfPeg: "PEG",
    dcfEvSales: "EV/Sales",
    dcfEvRevenueGrowth: "EV/Revenue Growth",
    dcfRevenueGrowth: "营收增速",
    dcfEarningsGrowth: "盈利增速",
    dcfGrossMargin: "毛利率",
    dcfOperatingMargin: "营业利润率",
    dcfMarginTrend: "利润率趋势",
    dcfMarketImplied: "市场隐含增长",
    dcfContextNote: "没有单一指标能给估值下定论。关键是比较市场正在定价什么，以及增长和利润率是否能支撑这种预期。",
    dcfBankWarning: "银行和金融公司更适合用剩余收益模型或 P/B 估值，不适合经典 FCF DCF。",
    dcfReitWarning: "REITs 更适合用 FFO/AFFO 估值，不适合经典 FCF DCF。",
    dcfSensitivityTitle: "敏感性分析 · 三档场景",
    dcfConservative: "保守",
    dcfBase: "中性",
    dcfOptimistic: "激进",
    dcfGrowthLabel: "增长率",
    dcfVsMarket: "vs 市场",
    dcfNotAvailable: "不可用",
    usMarket: "美股",
    cnMarket: "A 股",
    hkMarket: "港股",
    footerDisclaimer: "本工具仅供学习使用，所有内容不构成投资建议。",
    backToHome: "返回首页",
    loading: "加载中...",
  },
};

export function t(key: string, lang: Lang, vars?: Record<string, string | number>): string {
  let s = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return s;
}

export function useT() {
  const { lang } = useApp();
  return (key: string, vars?: Record<string, string | number>) => t(key, lang, vars);
}
