/**
 * Global App Context
 * Manages: theme (light / dark / system), language (zh / en), market (us / cn / hk)
 *
 * Default language: English
 * Default market: US
 */

"use client";

import {
  createContext,
  useContext,
  useEffect,
  useSyncExternalStore,
  ReactNode,
} from "react";

export type Theme = "light" | "dark" | "system";
export type Lang = "zh" | "en";
export type Market = "us" | "cn" | "hk";

const STORAGE_KEY = "fin-agent-prefs";
const PREFS_CHANGE_EVENT = "fin-agent-prefs-change";
const DEFAULT_PREFS = { theme: "system" as Theme, lang: "en" as Lang, market: "us" as Market };
let cachedPrefsRaw: string | null = null;
let cachedPrefsValue = DEFAULT_PREFS;

interface AppContextValue {
  theme: Theme;
  lang: Lang;
  market: Market;
  setTheme: (t: Theme) => void;
  setLang: (l: Lang) => void;
  setMarket: (m: Market) => void;
}

const AppContext = createContext<AppContextValue | null>(null);

function readPrefs(): { theme: Theme; lang: Lang; market: Market } {
  if (typeof window === "undefined") return DEFAULT_PREFS;
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === cachedPrefsRaw) return cachedPrefsValue;
    cachedPrefsRaw = saved;
    cachedPrefsValue = saved ? { ...DEFAULT_PREFS, ...JSON.parse(saved) } : DEFAULT_PREFS;
    return cachedPrefsValue;
  } catch {
    return DEFAULT_PREFS;
  }
}

export function AppProvider({ children }: { children: ReactNode }) {
  const prefs = useSyncExternalStore(
    (onStoreChange) => {
      window.addEventListener("storage", onStoreChange);
      window.addEventListener(PREFS_CHANGE_EVENT, onStoreChange);
      return () => {
        window.removeEventListener("storage", onStoreChange);
        window.removeEventListener(PREFS_CHANGE_EVENT, onStoreChange);
      };
    },
    readPrefs,
    () => DEFAULT_PREFS
  );
  const { theme, lang, market } = prefs;

  useEffect(() => {
    const root = document.documentElement;
    const apply = (t: Theme) => {
      const isDark =
        t === "dark" ||
        (t === "system" &&
          window.matchMedia("(prefers-color-scheme: dark)").matches);
      root.classList.toggle("dark", isDark);
    };
    apply(theme);
    if (theme === "system") {
      const mq = window.matchMedia("(prefers-color-scheme: dark)");
      const handler = () => apply("system");
      mq.addEventListener("change", handler);
      return () => mq.removeEventListener("change", handler);
    }
  }, [theme]);

  const persist = (next: { theme: Theme; lang: Lang; market: Market }) => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
      window.dispatchEvent(new Event(PREFS_CHANGE_EVENT));
    } catch {}
  };

  const setTheme = (t: Theme) => persist({ theme: t, lang, market });
  const setLang = (l: Lang) => persist({ theme, lang: l, market });
  const setMarket = (m: Market) => persist({ theme, lang, market: m });

  return (
    <AppContext.Provider value={{ theme, lang, market, setTheme, setLang, setMarket }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used inside AppProvider");
  return ctx;
}

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    brand: "fin-agent-pro",
    navMarketUS: "US Stocks",
    navMarketCN: "China A",
    navMarketHK: "Hong Kong",
    navPortfolio: "Portfolio",
    navCompare: "Compare",
    navValuation: "Valuation",
    navAnalysis: "AI Analysis",
    navSettings: "Settings",
    heroTitle: "fin-agent-pro",
    heroSubtitle: "AI-powered risk detection for the stocks you don't have time to analyze.",
    heroCTAPrimary: "Try a demo",
    heroCTASecondary: "Learn more",
    heroVisualKnownLabel: "Known signals",
    heroVisualKnownBody: "Revenue, margins, cash flow, leverage — the parts that can be checked against reality.",
    heroVisualUnknownLabel: "Unknown boundary",
    heroVisualUnknownBody: "Future shocks, regime shifts, hidden risks — named rather than disguised as certainty.",
    heroVisualEyebrow: "Honest financial analysis for retail investors",
    heroVisualTitle: "The financial AI that admits what it doesn't know.",
    learnMore: "Learn more",
    tryIt: "Try it",

    // Feature sections (homepage scroll narrative)
    featMarketEyebrow: "MARKET OVERVIEW",
    featMarketTitle: "Real-time market pulse.",
    featMarketBody: "S&P 500, NASDAQ, Hang Seng — all in one view. See what's moving across markets at a glance, with currency-aware formatting and live percentage changes.",

    featHeatmapEyebrow: "SECTOR HEATMAP",
    featHeatmapTitle: "See the heat.",
    featHeatmapBody: "News lags. Trading behavior doesn't. This map shows where capital and volatility are concentrating right now — not what to buy, but where to look.",

    featAiEyebrow: "AI FINANCIAL ANALYSIS",
    featAiTitle: "30 seconds. Any company.",
    featAiBody: "Powered by Altman Z-Score, Beneish M-Score, and Claude / GPT-4o. Ask in plain English, get a pro-grade risk read with red flags surfaced — institutional rigor, retail accessibility.",

    featCompareEyebrow: "MULTI-COMPANY COMPARE",
    featCompareTitle: "Side-by-side, Apple-style.",
    featCompareBody: "Compare 2 to 4 companies across financials, risk scores, and valuation multiples. Best-value highlights instantly show you the outlier — the way Apple compares iPhones.",

    featPortfolioEyebrow: "PORTFOLIO DIAGNOSTIC",
    featPortfolioTitle: "Know your concentration.",
    featPortfolioBody: "Weighted risk scoring, sector concentration warnings, red flags per holding. Your portfolio's full X-ray — diagnostic only, never advice. Data stays in your browser.",

    featDcfEyebrow: "DCF VALUATION",
    featDcfTitle: "Build the model in seconds.",
    featDcfBody: "Set WACC, growth, and terminal growth — see intrinsic value plus three sensitivity scenarios. The DCF model that took your finance professor a lecture, now ten clicks.",
    marketOverviewTitle: "Market Overview",
    marketOverviewSubtitle: "Live indices, sector pulse, and what's moving today.",
    sectorHeatmapTitle: "Sector Heatmap",
    sectorHeatmapSubtitle: "Bigger bubble = more attention · Deeper color = more volatile",
    heatmapBehaviorMantra: "News lags. Trading behavior doesn't.",
    heatmapBehaviorBody: "This map shows where capital and volatility are concentrating right now — not what to buy, but where to look.",
    sectorRankingTitle: "Sector Ranking",
    hkAnalysisTitle: "Analyze any HK-listed company",
    hkAnalysisBody: "Sector heatmaps aren't available for Hong Kong, but you can ask the AI about any HK-listed stock — Tencent (00700), HSBC (00005), Alibaba HK (09988), Xiaomi (01810), and more. Get the same Altman Z-Score / Beneish M-Score / financial breakdown.",
    hkAnalysisCTA: "Ask the AI",
    dataUnavailableTitle: "Market data temporarily unavailable",
    dataUnavailableBody: "The data provider (EastMoney via AkShare) is currently not responding. This is on their side, not yours. AI analysis on individual stocks still works — try the floating chat below.",
    cnFallbackTitle: "Analyze any A-share company",
    cnFallbackBody: "Market overview is currently unavailable, but you can still ask the AI about any A-share stock — Kweichow Moutai (600519), CATL (300750), BYD (002594), and more. Full financial breakdown with Altman Z-Score and Beneish M-Score.",
    cnFallbackCTA: "Ask the AI",
    catIndustry: "Industry",
    catSize: "Size",
    catRegion: "Region",
    viewHeatmap: "Heatmap",
    viewRank: "Ranking",
    todayHottest: "Today's hottest:",
    legendUp: "Up",
    legendDown: "Down",
    legendFlat: "Flat",
    clickHint: "Click any sector to see its top holdings · Updated every 30 minutes",
    sectorCol: "Sector",
    priceCol: "Price",
    changeCol: "Change %",
    inflowCol: "Net Inflow (B)",
    actionCol: "Action",
    viewDetail: "View detail",
    noData: "No data available",
    sectorHistory: "90-Day Trend",
    topHoldings: "Top 5 Holdings",
    chatTitle: "AI Financial Analysis",
    chatPrompt: "Ask me anything about a company's financials",
    chatHint: "I'll pull the latest data and tell you in 30 seconds whether the company is worth your attention.",
    chatPlaceholder: "e.g. Analyze Apple's 2024 financials",
    sectorChatPrompt: "Ask me what is moving this sector",
    sectorChatHint: "I'll map the move, likely drivers, key companies, and what remains uncertain.",
    sectorChatPlaceholder: "e.g. Analyze Technology / 科技 (XLK) and the key companies driving this move",
    loadingMsg: "Analyzing... fetching financial data + AI interpretation, may take 15-30 seconds",
    errorTitle: "Analysis failed",
    errorHint: "Please verify your API key or try again later.",
    identified: "Identified",
    aiDetail: "Detailed AI analysis",
    sectorAiDetail: "Sector radar readout",
    sectorRadarEyebrow: "Sector Radar",
    sectorRadarTitle: "Sector move detected",
    sectorRadarSubtitle: "A board-level read of the theme: what moved, who is driving it, and where uncertainty still lives.",
    sectorRadarMode: "Sector mode",
    sectorRadarMove: "Move",
    sectorRadarMoveBody: "What changed in the sector and why the market is paying attention.",
    sectorRadarCompanies: "Drivers",
    sectorRadarCompaniesBody: "Representative companies likely shaping the move.",
    sectorRadarUnknowns: "Unknowns",
    sectorRadarUnknownsBody: "What the current signal still cannot prove.",
    settingsBtn: "Configured",
    settingsBtnEmpty: "Configure AI",
    chatFloatingTitle: "Ask AI",
    chatExpand: "Expand",
    chatCollapse: "Collapse",
    riskLow: "Low Risk",
    riskMedium: "Medium Risk",
    riskHigh: "High Risk",
    riskScoreLabel: "Risk score / 100",
    riskBasedOn: "Based on Altman Z-Score, Beneish M-Score, cash flow quality, and other models",
    redFlagsTitle: "{n} signals to watch",
    radarTitle: "5-Dimension Health",
    radarSubtitle: "Each dimension scored 0-100, higher is healthier",
    dimProfitability: "Profitability",
    dimSolvency: "Solvency",
    dimCashFlow: "Cash Flow",
    dimRevenueQuality: "Revenue Quality",
    dimValuation: "Valuation",
    metricAltman: "Altman Z-Score",
    metricAltmanSub: "Bankruptcy risk prediction",
    metricBeneish: "Beneish M-Score",
    metricBeneishSub: "Earnings manipulation detection",
    metricCash: "Cash Flow Match",
    metricCashSub: "Earnings quality",
    metricAR: "AR Growth Rate",
    metricARSub: "Revenue authenticity",
    settingsTitle: "Settings",
    settingsAi: "AI Provider",
    settingsApiKey: "API Key",
    settingsTheme: "Theme",
    settingsLanguage: "Language",
    settingsMarket: "Default Market",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    keyHint: "Your key is stored only in your browser, never uploaded.",
    cancel: "Cancel",
    save: "Save",
    compareTitle: "Compare Companies",
    compareSubtitle: "Side-by-side comparison of 2-4 companies, Apple-style",
    compareHeaderSubtitle: "Add 2-4 tickers to compare side-by-side",
    compareTickerPlaceholder: "e.g. AAPL, MSFT, GOOGL, 600519...",
    compareAdd: "Add",
    compareRun: "Compare",
    compareNeed2: "Need at least 2 companies",
    compareMax4: "Max 4 companies",
    compareAlready: "Already added",
    compareExportPDF: "Export PDF",
    compareRiskScore: "Risk Score",
    compareDimensions: "5-Dimension Health",
    compareDimHint: "Higher is healthier",
    compareGroupOverview: "Financial Overview",
    compareGroupProfit: "Profitability",
    compareGroupBalance: "Balance Sheet",
    compareGroupCashflow: "Cash Flow",
    compareBestValue: "Best value among compared",
    comparePeriod: "Period",
    compareFailed: "Failed to compare",
    exportPdf: "Export PDF",
    exportPdfReport: "Export PDF Report",
    tickerRequired: "Ticker is required",
    portfolioTitle: "My Portfolio",
    portfolioSubtitle: "Diagnose your holdings — weighted risk, sector concentration, individual signals. Stored locally.",
    portfolioHeaderTitle: "My Portfolio · AI Diagnosis",
    portfolioHeaderSubtitle: "Enter your holdings to get a weighted risk diagnosis. Stored locally in your browser.",
    portfolioTickerPh: "Ticker (AAPL, 600519, 00700...)",
    portfolioAmountPh: "Position size ($, optional)",
    portfolioAdd: "Add",
    portfolioMax: "Max 15 holdings",
    portfolioClearAll: "Clear all",
    portfolioTotal: "Total",
    portfolioDiagnose: "Diagnose My Portfolio",
    portfolioAnalyzing: "Analyzing portfolio...",
    portfolioNeedHolding: "Add at least one holding",
    portfolioWeightedRisk: "Portfolio Risk / 100",
    portfolioSummaryDisclaimer: "Diagnostic only — not investment advice.",
    portfolioSignals: "Individual Stock Signals",
    portfolioSectorConcentration: "Sector Concentration",
    portfolioGeoDistribution: "Geographic Distribution",
    portfolioHoldings: "Holdings Detail",
    portfolioRemoveConfirm: "Remove all holdings?",
    portfolioDiagnosisFailed: "Diagnosis failed",
    portfolioPublicDataDisclaimer: "Diagnostic only — not investment advice. All conclusions are based on public financial data.",
    portfolioSomeDataMissing: "Some data couldn't be loaded:",
    portfolioTickerCol: "Ticker",
    portfolioNameCol: "Name",
    portfolioSectorCol: "Sector",
    portfolioWeightCol: "Weight",
    dcfTitle: "DCF Valuation",
    dcfHeaderTitle: "Model Builder · DCF Valuation",
    dcfSubtitle: "Two-stage DCF valuation with WACC build-up, net debt adjustment, and implied growth",
    dcfTicker: "Ticker",
    dcfTickerPlaceholder: "AAPL, MSFT, TSLA...",
    dcfWacc: "Discount Rate (WACC)",
    dcfWaccLoading: "Calculating suggested WACC...",
    dcfWaccSuggested: "Suggested by CAPM + capital structure",
    dcfWaccHint: "Higher = more conservative",
    dcfGrowth: "Stage 1 FCF Growth (5y)",
    dcfGrowthHint: "Annual FCF growth assumption",
    dcfGrowthTooltipTitle: "How we estimate growth",
    dcfGrowthTooltipBody: "The default uses recent earnings growth first, then revenue growth if earnings growth is unavailable. For high-growth technology companies, the cap rises to 45%; otherwise it is capped at 25%. If live data is missing, we fall back to 5%.",
    dcfGrowthTooltipCaution: "This is a scenario input, not a forecast. Change it when your view of future cash-flow growth differs from recent fundamentals.",
    dcfTerminal: "Terminal Growth",
    dcfTerminalHint: "Long-term GDP-like growth",
    dcfTerminalTooltipTitle: "Why GDP-like growth",
    dcfTerminalTooltipBody: "Terminal growth represents the steady-state growth rate after the explicit forecast period. We default to 2.5% because a mature company should not outgrow the economy forever.",
    dcfTerminalTooltipCaution: "Keep terminal growth below WACC. Small changes here can move valuation sharply because it drives the terminal value.",
    dcfRun: "Run DCF Valuation",
    dcfRunning: "Calculating...",
    dcfIntrinsic: "Intrinsic Value",
    dcfIntrinsicSub: "per share",
    dcfCurrent: "Current Price",
    dcfCurrentSub: "market price",
    dcfUpside: "Upside / Downside",
    dcfUndervalued: "above market under these inputs",
    dcfOvervalued: "below market under these inputs",
    dcfAssumptionTitle: "Assumption-sensitive result.",
    dcfAssumptionBody: "DCF can be unreliable for hyper-growth stocks; this value reflects {growth}% near-term FCF growth and a {discount}% discount rate.",
    dcfMarketImplies: "Market price implies roughly {implied} Stage 1 growth in this model.",
    dcfCompareImplied: "Compare the implied growth with your own view of the business.",
    dcfFcfProjection: "10-Year Two-Stage FCF Projection (Present Value, $B)",
    dcfYear: "Year",
    dcfFutureFcf: "FCF (Future)",
    dcfPresentValue: "Present Value",
    dcfCurrentFcf: "Current FCF",
    dcfTerminalValuePv: "Terminal Value (PV)",
    dcfEnterpriseValue: "Enterprise Value",
    dcfEquityValue: "Equity Value",
    dcfSharesOut: "Shares Out",
    dcfNetDebt: "Net Debt",
    dcfNetCash: "Net Cash",
    dcfTerminalPct: "Terminal % of EV",
    dcfImpliedGrowth: "Implied Growth",
    dcfSuggestedWacc: "Suggested WACC",
    dcfRiskFree: "Risk-free rate (10Y T)",
    dcfBeta: "Beta",
    dcfRawBeta: "Raw beta",
    dcfEquityRiskPremium: "Equity risk premium",
    dcfCostOfEquity: "Cost of equity",
    dcfCostOfDebt: "Cost of debt (after tax)",
    dcfTaxRate: "Tax rate",
    dcfMarketCapWeight: "Market cap weight",
    dcfDebtWeight: "Debt weight",
    dcfGrowthProfile: "Growth-sensitive default",
    dcfGrowthProfileBody: "For high-growth technology companies, defaults now use recent fundamental growth with a higher growth ceiling and Blume-adjusted beta. Treat it as a starting scenario, not a target price.",
    dcfContextTitle: "Valuation context",
    dcfContextSubtitle: "For high-growth companies, read DCF alongside multiples, growth quality, margins, and market-implied expectations.",
    dcfThreeAnswersTitle: "Three answers, one uncertainty",
    dcfOurDcfAnswer: "Our DCF",
    dcfMarketAnswer: "Market price",
    dcfAnalystAnswer: "Wall St. target",
    dcfAnalystCount: "{n} analysts",
    dcfTargetRange: "Target range",
    dcfRecommendation: "Consensus",
    dcfDisagreementSignal: "These answers can disagree sharply. That disagreement is the signal: DCF, market price, and analyst targets are different lenses, not certain truth.",
    dcfAnalystCaveat: "Analyst targets can be stale or optimistic, so treat them as a second opinion rather than the answer.",
    dcfViewAnalysts: "View analyst coverage",
    dcfAnalystDrawerTitle: "Wall St. coverage",
    dcfAnalystDrawerSubtitle: "Recent yfinance rating actions and target-price consensus. Availability varies by ticker.",
    dcfAnalystFirm: "Firm",
    dcfAnalystAction: "Action",
    dcfAnalystToGrade: "To grade",
    dcfAnalystFromGrade: "From",
    dcfNoAnalystEntries: "No recent firm-level rating actions available from yfinance.",
    dcfHighGrowthWarning: "High-growth profile detected: DCF can become extremely unstable. Treat the intrinsic value as a scenario output, not a verdict.",
    dcfStability: "DCF stability",
    dcfUnstable: "Extremely unstable",
    dcfModerate: "Moderate",
    dcfForwardPe: "Forward P/E",
    dcfPeg: "PEG",
    dcfEvSales: "EV/Sales",
    dcfEvRevenueGrowth: "EV/Revenue Growth",
    dcfRevenueGrowth: "Revenue Growth",
    dcfEarningsGrowth: "Earnings Growth",
    dcfGrossMargin: "Gross Margin",
    dcfOperatingMargin: "Operating Margin",
    dcfMarginTrend: "Margin trend",
    dcfMarketImplied: "Market-implied Growth",
    dcfContextNote: "No single metric settles valuation. The point is to compare what the market is pricing against growth durability and margin quality.",
    dcfBankWarning: "Banks and financial companies are better valued with Residual Income or P/B models, not classic FCF DCF.",
    dcfReitWarning: "REITs are better valued with FFO/AFFO, not classic FCF DCF.",
    dcfSensitivityTitle: "Sensitivity Analysis · Three Scenarios",
    dcfConservative: "Conservative",
    dcfBase: "Base Case",
    dcfOptimistic: "Optimistic",
    dcfGrowthLabel: "Growth",
    dcfVsMarket: "vs market",
    dcfNotAvailable: "N/A",
    usMarket: "US Stocks",
    cnMarket: "China A-Shares",
    footerDisclaimer: "For educational use only. Nothing here constitutes investment advice.",
    backToHome: "Back to home",
    loading: "Loading...",
  },
  zh: {
    brand: "fin-agent-pro",
    navMarketUS: "美股",
    navMarketCN: "A 股",
    navMarketHK: "港股",
    navPortfolio: "投资组合",
    navCompare: "对比",
    navValuation: "估值",
    navAnalysis: "AI 分析",
    navSettings: "设置",
    heroTitle: "fin-agent-pro",
    heroSubtitle: "用 AI 帮你 30 秒看懂一家公司的风险——给没时间研究财报的你。",
    heroCTAPrimary: "试用演示",
    heroCTASecondary: "了解更多",
    heroVisualKnownLabel: "可验证信号",
    heroVisualKnownBody: "营收、利润率、现金流、负债——这些能被真实数据交叉验证的部分。",
    heroVisualUnknownLabel: "未知边界",
    heroVisualUnknownBody: "未来冲击、制度切换、隐性风险——被明确标出，而不是伪装成确定性。",
    heroVisualEyebrow: "散户能用的诚实金融分析",
    heroVisualTitle: "承认未知的金融 AI。",
    learnMore: "了解更多",
    tryIt: "立即体验",

    // 首页滚动叙事
    featMarketEyebrow: "大盘指数",
    featMarketTitle: "全球市场，一屏掌握。",
    featMarketBody: "标普 500、纳斯达克、恒生指数——一眼看尽。实时百分比变动 + 自动货币格式化，不用再切换 App 看不同市场。",

    featHeatmapEyebrow: "行业热度图",
    featHeatmapTitle: "热点一目了然。",
    featHeatmapBody: "新闻滞后，交易行为不会。这张图显示资金和波动当前聚集在哪——不是叫你买什么，而是告诉你该往哪看。",

    featAiEyebrow: "AI 财务分析",
    featAiTitle: "30 秒，看懂任何公司。",
    featAiBody: "Altman Z-Score、Beneish M-Score、Claude/GPT-4o 多模型驱动。用大白话提问，得到机构级风险解读和红旗预警——专业严谨，散户友好。",

    featCompareEyebrow: "多公司对比",
    featCompareTitle: "苹果风格的横向对比。",
    featCompareBody: "支持 2-4 家公司在财务、风险、估值维度并排对比。最优项自动高亮——就像苹果官网比较 iPhone 那样直观。",

    featPortfolioEyebrow: "投资组合诊断",
    featPortfolioTitle: "看清你的持仓集中度。",
    featPortfolioBody: "加权风险评分、行业集中度告警、个股红旗。给你的组合做一次全面体检——只诊断，不建议；数据永远不离开你的浏览器。",

    featDcfEyebrow: "DCF 估值",
    featDcfTitle: "10 次点击，搭好估值模型。",
    featDcfBody: "调整 WACC、增长率、终值增长——立刻看到内在价值和三档敏感性场景。当年财务课老师讲一节课的 DCF，现在拖几个滑块就够了。",
    marketOverviewTitle: "市场概览",
    marketOverviewSubtitle: "实时指数、板块脉搏、今日热点。",
    sectorHeatmapTitle: "行业热度地图",
    sectorHeatmapSubtitle: "气泡越大 = 资金越关注 · 颜色越深 = 波动越剧烈",
    heatmapBehaviorMantra: "新闻滞后，交易行为不会。",
    heatmapBehaviorBody: "这张图显示资金和波动当前聚集在哪——不是叫你买什么，而是告诉你该往哪看。",
    sectorRankingTitle: "板块排行",
    hkAnalysisTitle: "分析任何港股公司",
    hkAnalysisBody: "港股暂不支持行业热度图，但你可以让 AI 分析任何港股个股——腾讯 (00700)、汇丰 (00005)、阿里 (09988)、小米 (01810) 等。同样的 Altman Z-Score / Beneish M-Score / 财务全面解读。",
    hkAnalysisCTA: "问 AI",
    dataUnavailableTitle: "市场数据暂时不可用",
    dataUnavailableBody: "数据源（东方财富/AkShare）当前未响应，与你无关。个股 AI 分析仍然可用——可以使用右下角浮动对话框测试。",
    cnFallbackTitle: "分析任何 A 股公司",
    cnFallbackBody: "大盘数据暂不可用，但你仍可以让 AI 分析任何 A 股个股——贵州茅台 (600519)、宁德时代 (300750)、比亚迪 (002594) 等。完整财务解读 + Altman Z-Score + Beneish M-Score。",
    cnFallbackCTA: "问 AI",
    catIndustry: "行业",
    catSize: "市值",
    catRegion: "地域",
    viewHeatmap: "热度图",
    viewRank: "排行",
    todayHottest: "今日最热：",
    legendUp: "上涨",
    legendDown: "下跌",
    legendFlat: "持平",
    clickHint: "点击任何板块查看其领涨公司 · 数据每 30 分钟更新",
    sectorCol: "板块",
    priceCol: "价格",
    changeCol: "涨跌幅",
    inflowCol: "主力净流入(亿)",
    actionCol: "操作",
    viewDetail: "查看详情",
    noData: "暂无数据",
    sectorHistory: "近 90 天走势",
    topHoldings: "前 5 大成分股",
    chatTitle: "AI 财务分析",
    chatPrompt: "问我任何公司的财务问题",
    chatHint: "我会拉取最新财务数据，30 秒内告诉你这家公司值不值得关注",
    chatPlaceholder: "例：分析苹果 2024 年的财务状况",
    sectorChatPrompt: "问我这个板块为什么在动",
    sectorChatHint: "我会梳理板块异动、可能驱动因素、关键公司，以及仍然未知的部分。",
    sectorChatPlaceholder: "例：分析科技板块，以及推动本轮走势的关键公司",
    loadingMsg: "正在分析中... 拉取财务数据 + AI 解读，可能需要 15-30 秒",
    errorTitle: "分析出错",
    errorHint: "请检查 API Key 是否正确，或稍后重试。",
    identified: "已识别",
    aiDetail: "AI 详细解读",
    sectorAiDetail: "板块雷达解读",
    sectorRadarEyebrow: "板块雷达",
    sectorRadarTitle: "检测到板块异动",
    sectorRadarSubtitle: "先看整片天气：发生了什么、谁在驱动、哪些地方仍然看不清。",
    sectorRadarMode: "板块模式",
    sectorRadarMove: "异动",
    sectorRadarMoveBody: "这个板块发生了什么，市场为什么开始重新定价。",
    sectorRadarCompanies: "驱动",
    sectorRadarCompaniesBody: "最可能塑造本轮行情的代表公司。",
    sectorRadarUnknowns: "未知",
    sectorRadarUnknownsBody: "当前信号还无法证明的部分。",
    settingsBtn: "已配置",
    settingsBtnEmpty: "配置 AI",
    chatFloatingTitle: "问 AI",
    chatExpand: "展开",
    chatCollapse: "收起",
    riskLow: "低风险",
    riskMedium: "中等风险",
    riskHigh: "高风险",
    riskScoreLabel: "风险分 / 100",
    riskBasedOn: "基于 Altman Z-Score、Beneish M-Score、现金流质量等多维度模型评估",
    redFlagsTitle: "发现 {n} 项关注信号",
    radarTitle: "五维度健康度",
    radarSubtitle: "每个维度 0-100 分，越大越健康",
    dimProfitability: "盈利能力",
    dimSolvency: "偿债能力",
    dimCashFlow: "现金流",
    dimRevenueQuality: "营收质量",
    dimValuation: "估值",
    metricAltman: "Altman Z-Score",
    metricAltmanSub: "破产风险预测",
    metricBeneish: "Beneish M-Score",
    metricBeneishSub: "盈余操纵识别",
    metricCash: "现金流匹配度",
    metricCashSub: "盈利质量",
    metricAR: "应收账款增速",
    metricARSub: "营收真实性",
    settingsTitle: "设置",
    settingsAi: "AI 服务",
    settingsApiKey: "API Key",
    settingsTheme: "主题",
    settingsLanguage: "语言",
    settingsMarket: "默认市场",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    keyHint: "Key 只存于你的浏览器，不会上传任何服务器",
    cancel: "取消",
    save: "保存",
    compareTitle: "多公司对比",
    compareSubtitle: "Apple 风格的横向对比，支持 2-4 家公司",
    compareHeaderSubtitle: "添加 2-4 个股票代码进行横向对比",
    compareTickerPlaceholder: "例：AAPL、MSFT、GOOGL、600519...",
    compareAdd: "添加",
    compareRun: "对比",
    compareNeed2: "至少需要 2 家公司",
    compareMax4: "最多 4 家",
    compareAlready: "已经添加过了",
    compareExportPDF: "导出 PDF",
    compareRiskScore: "风险评分",
    compareDimensions: "五维度健康度",
    compareDimHint: "越高越健康",
    compareGroupOverview: "财务概览",
    compareGroupProfit: "盈利能力",
    compareGroupBalance: "资产负债",
    compareGroupCashflow: "现金流",
    compareBestValue: "对比中最优",
    comparePeriod: "财年",
    compareFailed: "对比失败",
    exportPdf: "导出 PDF",
    exportPdfReport: "导出 PDF 报告",
    tickerRequired: "请输入股票代码",
    portfolioTitle: "我的投资组合",
    portfolioSubtitle: "诊断你的持仓——加权风险、行业集中度、个股信号。数据本地存储。",
    portfolioHeaderTitle: "我的投资组合 · AI 诊断",
    portfolioHeaderSubtitle: "输入持仓后获得加权风险诊断。数据只保存在你的浏览器里。",
    portfolioTickerPh: "代码（AAPL、600519、00700...）",
    portfolioAmountPh: "仓位金额（$，可选）",
    portfolioAdd: "添加",
    portfolioMax: "最多 15 只",
    portfolioClearAll: "全部清空",
    portfolioTotal: "总计",
    portfolioDiagnose: "AI 诊断我的组合",
    portfolioAnalyzing: "正在诊断...",
    portfolioNeedHolding: "请至少添加一只持仓",
    portfolioWeightedRisk: "组合风险 / 100",
    portfolioSummaryDisclaimer: "仅作诊断参考——不构成投资建议。",
    portfolioSignals: "个股信号",
    portfolioSectorConcentration: "行业集中度",
    portfolioGeoDistribution: "地域分布",
    portfolioHoldings: "持仓明细",
    portfolioRemoveConfirm: "确认清空全部持仓？",
    portfolioDiagnosisFailed: "诊断失败",
    portfolioPublicDataDisclaimer: "仅作诊断参考——不构成投资建议。所有结论基于公开财务数据。",
    portfolioSomeDataMissing: "部分数据未能加载：",
    portfolioTickerCol: "代码",
    portfolioNameCol: "名称",
    portfolioSectorCol: "行业",
    portfolioWeightCol: "权重",
    dcfTitle: "DCF 估值",
    dcfHeaderTitle: "模型构建器 · DCF 估值",
    dcfSubtitle: "两阶段 DCF：包含 WACC、净负债调整、终值和隐含增长率",
    dcfTicker: "股票代码",
    dcfTickerPlaceholder: "AAPL、MSFT、TSLA...",
    dcfWacc: "折现率 (WACC)",
    dcfWaccLoading: "正在计算建议 WACC...",
    dcfWaccSuggested: "由 CAPM + 资本结构估算",
    dcfWaccHint: "越高越保守",
    dcfGrowth: "第一阶段自由现金流增速 (5 年)",
    dcfGrowthHint: "年化增速假设",
    dcfGrowthTooltipTitle: "我们如何推测增速",
    dcfGrowthTooltipBody: "默认优先使用近期 earnings growth；如果没有，就使用 revenue growth。高增长科技公司上限放宽到 45%；其他公司上限为 25%。如果实时数据缺失，则回退到 5%。",
    dcfGrowthTooltipCaution: "这是场景输入，不是预测结论。如果你对未来现金流增速的判断不同，可以手动调整。",
    dcfTerminal: "终值增长率",
    dcfTerminalHint: "长期 GDP 类增长",
    dcfTerminalTooltipTitle: "为什么用 GDP 类增长",
    dcfTerminalTooltipBody: "终值增长率代表明确预测期之后的稳定增长。默认 2.5%，因为成熟公司不应该被假设为永远跑赢整个经济。",
    dcfTerminalTooltipCaution: "终值增长率必须低于 WACC。它会影响终值，哪怕小幅变化也可能显著改变估值。",
    dcfRun: "运行 DCF",
    dcfRunning: "计算中...",
    dcfIntrinsic: "内在价值",
    dcfIntrinsicSub: "每股",
    dcfCurrent: "当前价格",
    dcfCurrentSub: "市场价",
    dcfUpside: "上涨 / 下跌空间",
    dcfUndervalued: "在这些假设下高于市场价",
    dcfOvervalued: "在这些假设下低于市场价",
    dcfAssumptionTitle: "结果对假设高度敏感。",
    dcfAssumptionBody: "DCF 对高增长股票并不稳定；这个估值使用了 {growth}% 近期自由现金流增速和 {discount}% 折现率。",
    dcfMarketImplies: "在这个模型里，市场价格隐含约 {implied} 的第一阶段增长率。",
    dcfCompareImplied: "请把隐含增长率与你对公司的判断放在一起看。",
    dcfFcfProjection: "10 年两阶段自由现金流预测（现值，$B）",
    dcfYear: "年份",
    dcfFutureFcf: "未来 FCF",
    dcfPresentValue: "现值",
    dcfCurrentFcf: "当前 FCF",
    dcfTerminalValuePv: "终值现值",
    dcfEnterpriseValue: "企业价值",
    dcfEquityValue: "股权价值",
    dcfSharesOut: "流通股本",
    dcfNetDebt: "净债务",
    dcfNetCash: "净现金",
    dcfTerminalPct: "终值占 EV",
    dcfImpliedGrowth: "隐含增长率",
    dcfSuggestedWacc: "建议 WACC",
    dcfRiskFree: "无风险利率（10 年期美债）",
    dcfBeta: "调整后 Beta",
    dcfRawBeta: "原始 Beta",
    dcfEquityRiskPremium: "股权风险溢价",
    dcfCostOfEquity: "股权成本",
    dcfCostOfDebt: "债务成本（税后）",
    dcfTaxRate: "税率",
    dcfMarketCapWeight: "市值权重",
    dcfDebtWeight: "债务权重",
    dcfGrowthProfile: "高增长默认假设",
    dcfGrowthProfileBody: "对高增长科技公司，默认值现在会参考近期基本面增长，并使用更高的增长上限和 Blume 调整 Beta。它是起始场景，不是目标价。",
    dcfContextTitle: "估值上下文",
    dcfContextSubtitle: "对高增长公司，要把 DCF 与估值倍数、增长质量、利润率和市场隐含预期放在一起看。",
    dcfThreeAnswersTitle: "三个答案，一个不确定性",
    dcfOurDcfAnswer: "我们的 DCF",
    dcfMarketAnswer: "市场价格",
    dcfAnalystAnswer: "华尔街目标价",
    dcfAnalystCount: "{n} 位分析师",
    dcfTargetRange: "目标价区间",
    dcfRecommendation: "共识评级",
    dcfDisagreementSignal: "这些答案可能剧烈分歧。分歧本身就是信号：DCF、市场价格和机构目标价是三种视角，不是确定真相。",
    dcfAnalystCaveat: "分析师目标价可能滞后或偏乐观，所以它只是第二意见，不是正确答案。",
    dcfViewAnalysts: "查看分析师覆盖",
    dcfAnalystDrawerTitle: "华尔街覆盖记录",
    dcfAnalystDrawerSubtitle: "来自 yfinance 的近期评级动作与目标价共识。不同股票可用字段会不同。",
    dcfAnalystFirm: "机构",
    dcfAnalystAction: "动作",
    dcfAnalystToGrade: "当前评级",
    dcfAnalystFromGrade: "此前评级",
    dcfNoAnalystEntries: "yfinance 暂无近期机构级评级动作。",
    dcfHighGrowthWarning: "检测到高增长特征：DCF 会变得极不稳定。请把内在价值视为情景输出，而不是定论。",
    dcfStability: "DCF 稳定性",
    dcfUnstable: "极不稳定",
    dcfModerate: "中等",
    dcfForwardPe: "Forward P/E",
    dcfPeg: "PEG",
    dcfEvSales: "EV/Sales",
    dcfEvRevenueGrowth: "EV/Revenue Growth",
    dcfRevenueGrowth: "营收增速",
    dcfEarningsGrowth: "盈利增速",
    dcfGrossMargin: "毛利率",
    dcfOperatingMargin: "营业利润率",
    dcfMarginTrend: "利润率趋势",
    dcfMarketImplied: "市场隐含增长",
    dcfContextNote: "没有单一指标能给估值下定论。关键是比较市场正在定价什么，以及增长和利润率是否能支撑这种预期。",
    dcfBankWarning: "银行和金融公司更适合用剩余收益模型或 P/B 估值，不适合经典 FCF DCF。",
    dcfReitWarning: "REITs 更适合用 FFO/AFFO 估值，不适合经典 FCF DCF。",
    dcfSensitivityTitle: "敏感性分析 · 三档场景",
    dcfConservative: "保守",
    dcfBase: "中性",
    dcfOptimistic: "激进",
    dcfGrowthLabel: "增长率",
    dcfVsMarket: "vs 市场",
    dcfNotAvailable: "不可用",
    usMarket: "美股",
    cnMarket: "A 股",
    footerDisclaimer: "本工具仅供学习使用，所有内容不构成投资建议。",
    backToHome: "返回首页",
    loading: "加载中...",
  },
};

export function t(key: string, lang: Lang, vars?: Record<string, string | number>): string {
  let s = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return s;
}

export function useT() {
  const { lang } = useApp();
  return (key: string, vars?: Record<string, string | number>) => t(key, lang, vars);
}
